deriv-com/bot

- .github/CODEOWNERS
- package.json
- src/pages/home/index.tsx
1. Added code owners
2. Updated devDependencies and dependencies list
3. Update home text to see if the CICD works or not
> chore: :sparkle: added codeoweners and updated deps

- package-lock.json
- package.json
- src/app/app-content.jsx
- src/app/index.ts
- src/external/bot-skeleton/services/api/active-symbols.js
- src/external/bot-skeleton/services/api/api-base.js
- src/external/bot-skeleton/services/api/trading-times.js
- src/external/bot-skeleton/services/tradeEngine/trade/Balance.js
- src/hooks/useStore.tsx
- src/stores/app-store.ts
- src/stores/index.ts
- src/stores/self-exclusion-store.ts
- vite.config.ts
Previously we used the WS connection that was coming from the core. In this PR we tried to utilise API base to replace that usage.
> [BOT] chore: remove core ws connection

- package-lock.json
- package.json
- src/external/bot-skeleton/services/api/ticks_service.js
- src/external/bot-skeleton/services/tradeEngine/trade/Ticks.js
- src/external/bot-skeleton/utils/binary-utils.ts
- Removed usage of binary-utils package since the repo is archived and cannot be updated
- Added the utility functions locally to avoid adding the external package
> chore: :fire: updated outdated babel packages and removed binary-utils

- public/assets/icons/IcFilter.svg
- src/components/download/download.scss
- src/components/journal/journal-components/filters.tsx
- src/components/journal/journal-components/journal-tools.tsx
- src/components/journal/journal.scss
- src/components/journal/journal.tsx
- src/components/summary/summary-card.scss
- src/components/summary/summary-card.tsx
- src/components/transactions/transactions.scss
- src/components/transactions/transactions.tsx
##Changes:
- make a working journal tab of the run panel
- adapt filters
- fix styles of text content
> [APP SEPARATION] [BOT] / maryia / feat: make work journal tab of run panel, adapt filters, text content

- src/components/layout/header/account-switcher.tsx
- src/components/layout/header/header.scss
- src/hooks/api/account/useAccountList.tsx
- src/stores/app-store.ts
Fixed the blockly block reference on account switching.
Added disabled state for disabled account.
> fix: account switcher disabled item showing as active

- src/app/app.scss
- src/components/layout/footer/footer.scss
- src/pages/chart/chart.scss
- src/pages/chart/chart.tsx
- src/pages/chart/toolbar-widgets.tsx
- src/stores/chart-store.ts
We had an issue with re-renders when switching tabs, which caused the chart to stop functioning. During these re-renders, the two functions requestForget={() => {}} and requestForgetStream={() => {}} were being called unnecessarily. To resolve this, I removed those calls and now handle the logic manually in the requestSubscribe function.
When a new symbol call is triggered, I call the forget ws call for the old subscription ID, and updateing i the new subscription ID as well in the store. This way, we manage the subscriptions ourselves.
requestForgetStream(chartSubscriptionIdRef.current);
const history = await chart_api.api.send(req);
setChartSubscriptionId(history?.subscription.id);
2. The subscription ID is stored in chart-store.
Moreover, I couldn't delete the mandatory functions from …
> [BOT] Mayuran/bot-2268/Address chart overlap and other chart  issues and UI issues

- src/app/CoreStoreProvider.tsx
- src/components/layout/header/account-switcher.tsx
- src/external/bot-skeleton/services/api/api-base.ts
- src/pages/main/main.tsx
This pull request includes various improvements and bug fixes across multiple files. The key changes involve fixing the **functionality to show a reload modal if the WS connection got dropped while the bot is running**, renaming a function for clarity, adding error handling for authorization, and cleaning up unused code. Additionally, several refactors were made to improve the codebase.
* [`src/app/CoreStoreProvider.tsx`](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8L84-R101): Renamed `handleMessage` to `handleMessages` and added error handling for `AuthorizationRequired` errors. [[1]](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8L84-R101) [[2]](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be …
> chore: fix reload on device wakeup if bot was running

- package-lock.json
- package.json
- src/components/shared_ui/contract-card/contract-card-items/contract-type-cell.tsx
- src/components/trade-type/trade-type-icon.tsx
- src/components/transaction-details/desktop-transaction-table.tsx
- src/components/transaction-details/mobile-transaction-card.tsx
- src/components/transactions/transaction.tsx
- src/components/transactions/transactions.scss
- Added all the trade type icons from quill icons to summary and transaction tabs.
> Farabi/bot-2371/fix-trade-type-icons-in-run-panel 

- src/app/app-content.jsx
- src/components/tnc-status-update-modal/index.ts
- src/components/tnc-status-update-modal/tnc-status-update-modal.scss
- src/components/tnc-status-update-modal/tnc-status-update-modal.tsx
- src/hooks/useIsTNCNeeded.ts
- src/stores/client-store.ts
- Added terms and conditions modal
- Added terms and conditions check hook
- on Click of the continue button on dialog, it will be updated in backend
> feat: :fire: added terms and conditions dialog

- src/stores/summary-card-store.ts
fix: Run panel animation result does not match contact result on win/loss
!we need the value of each transaction of the profit field relative to one contract, not just the first one
> maryia/fix: Run panel animation result does not match contact result on win/loss

- package-lock.json
- package.json
This pull request includes a minor update to the `package.json` file. The change updates the version of the `@deriv-com/auth-client` dependency.
Dependency update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L25-R25): Updated `@deriv-com/auth-client` from version `^1.2.12` to `^1.2.13`.
> chore: update auth client version

- src/components/draggable/draggable.tsx
This pull request includes a change to the `Draggable` component in the `src/components/draggable/draggable.tsx` file. The change improves the handling of the draggable content's style when dragging ends.
* [`src/components/draggable/draggable.tsx`](diffhunk://#diff-e4dd126ff7597c535e22f5bdeacd431c5629133012bcfc552d38e3309f02b516R179-R183): Added a `try-catch` block around the `Object.assign` call to handle potential errors and ensure `pointerEvents` is reset to 'unset' if an error occurs.
> fix: draggable component stuck issue

- src/pages/dashboard/announcements/announcements.tsx
- src/pages/tutorials/dbot-tours/bot-builder-tour/bot-builder-tour-desktop.tsx
1) fix: The button "Import strategy" does not work on the "Moving strategies to Deriv Bot" announcement modal
2) fix: Appearance of the tour modal window after we open the download modal window and switch to the bot builder page on the background
https://github.com/user-attachments/assets/97174cd8-6456-4f21-84cd-be062dda959c
> maryia/BOT-2605/fix: The button "Import strategy" does not work on the "Moving strategies to Deriv Bot" announcement modal

- src/external/bot-skeleton/scratch/dbot.js
- src/external/bot-skeleton/scratch/utils/index.js
- src/external/bot-skeleton/utils/error-config.js
- src/external/bot-skeleton/utils/error-handling.js
This pull request focuses on refactoring and improving the error handling and context menu functionalities in the bot-skeleton project. The key changes include refactoring the `error_message_map` to be a function, updating context menu options to be functions, and enhancing the error handling mechanism.
* Refactored `error_message_map` to be a function that returns the error messages. This change ensures that the error messages are dynamically generated. [[1]](diffhunk://#diff-ab461a4c0c08e5d31e10a312be92c13a1294965a6b6b14a037f840b647901e20L1-R21) [[2]](diffhunk://#diff-ab461a4c0c08e5d31e10a312be92c13a1294965a6b6b14a037f840b647901e20L51-R30)
* Updated error handling in `handleError` to use the refactored `error_message_map` function.
* Changed `download_option`, `deleteBlocksLocaleText`, …
> fix: context menu issues

- src/utils/datadog.ts
This pull request includes a small change to the `src/utils/datadog.ts` file. The change adds a console log statement to display the current environment when initializing Datadog.
* [`src/utils/datadog.ts`](diffhunk://#diff-e6d498e4558d9849d4a0e014065f481982232fd4fc06566e2f53f5b8271f3b0bR28): Added a console log statement to print the current environment (`process.env.NODE_ENV`) during Datadog initialization.
> chore: test workflow

- .github/workflows/build-and-deploy-staging.yml
- src/utils/datadog.ts
This pull request includes changes to the build and deployment process for the staging environment and some cleanup in the `datadog` utility file. The most important changes are listed below:
* [`.github/workflows/build-and-deploy-staging.yml`](diffhunk://#diff-b709f2739a5258d6c2c45e190ddc8e9329c2492822f44b593a8de5145e930b42R42): Added `NODE_ENV: staging` to the environment variables for the staging build job.
* [`src/utils/datadog.ts`](diffhunk://#diff-e6d498e4558d9849d4a0e014065f481982232fd4fc06566e2f53f5b8271f3b0bL28): Removed a console log statement that printed the current environment.
> chore: fix staging workflow

- .github/workflows/build-and-deploy-staging.yml
This pull request includes a small change to the `.github/workflows/build-and-deploy-staging.yml` file. The change sets the `NODE_ENV` environment variable to use the value from the repository's variables.
* [`.github/workflows/build-and-deploy-staging.yml`](diffhunk://#diff-b709f2739a5258d6c2c45e190ddc8e9329c2492822f44b593a8de5145e930b42R42): Added `NODE_ENV` environment variable to the build staging job.
> chore: check staging workflow with env vars

- src/constants/quick-strategies/d_alembert.ts
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/accumulator_take_profit.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/multiplier_stop_loss.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/multiplier_take_profit.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_accumulator.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js
- src/external/bot-skeleton/scratch/utils/index.js
- src/stores/app-store.ts
Fixed currecy on trade definition block. by updating to the new blockly method called setValue
> Rupato/BOT-2436/fix: for currency on trade definition block

- src/pages/bot-builder/quick-strategy/quick-strategy.scss
- src/pages/dashboard/announcements/announcements.scss
fix: Minor CSS bugs on the announcements and quick strategy modal windows
1)
2)
> maryia/BOT-2616/fix: Minor CSS bugs on the announcements and quick strategy modal windows

- src/pages/tutorials/dbot-tours/tour-content.tsx
This pull request includes changes to the `src/pages/tutorials/dbot-tours/tour-content.tsx` file to improve the structure and readability of the tour content by wrapping `Localize` components inside `span` elements.
Changes to tour content:
* Wrapped `Localize` components inside `span` elements for `BOT_BUILDER_MOBILE` steps.
* Wrapped `Localize` components inside `span` elements for `DBOT_ONBOARDING_MOBILE` steps. [[1]](diffhunk://#diff-811dd990c95a89f81acdde37188a3c07fe2822c0bed9cd4b5eb409d8ffa16b2bR488-R532) [[2]](diffhunk://#diff-811dd990c95a89f81acdde37188a3c07fe2822c0bed9cd4b5eb409d8ffa16b2bR541-R585)
> fix: added span wrapper in tour config

- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js
This pull request includes a minor change to the `trade_definition_tradeoptions.js` file. The change ensures that the `stop_loss_block` is initialized and rendered before it is connected to the `multiplier_block`.
* [`src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js`](diffhunk://#diff-ddafb9ecab3f17ca1d9362d1c8e8d083b398ceb8b563eb1ee516fc999900d012R356-L360): Moved the initialization and rendering of `stop_loss_block` before its connection to `multiplier_block` to ensure proper execution order.
> fix: multiplier stop loss block

- src/app/app-content.jsx
- src/external/bot-skeleton/scratch/backward-compatibility.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_accumulator.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_market.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js
- src/external/bot-skeleton/scratch/dbot.js
- src/external/bot-skeleton/services/api/api-helpers.js
- src/pages/bot-builder/quick-strategy/selects/contract-type.tsx
- src/pages/bot-builder/quick-strategy/selects/duration-type.tsx
- src/pages/bot-builder/quick-strategy/selects/symbol.tsx
- src/pages/bot-builder/quick-strategy/selects/trade-type.tsx
- src/stores/app-store.ts
- src/stores/quick-strategy-store.ts
This pull request focuses on improving the robustness of the code by adding nullish coalescing and optional chaining operators to various instances of `ApiHelpers`. These changes ensure that the application handles cases where `ApiHelpers` or its properties might be undefined, preventing potential runtime errors.
Key changes include:
* [`src/app/app-content.jsx`](diffhunk://#diff-acb1b12c8798bdef78154e1bcbb70ce985402145ca80e436a5886cb66afed67fL125-R144): Replaced the interval-based loading of active symbols with a function that checks if `ApiHelpers.instance.active_symbols` is available and retrieves active symbols accordingly. Added a workaround for cases where active symbols are not immediately loaded.
* [`src/external/bot-skeleton/scratch/backward-compatibility.js`](diffhunk://#diff-3e8 …
> fix: hotfix active symbol issue

- src/hooks/useTrackjs.ts
This pull request includes an update to the `useTrackjs` hook in the `src/hooks/useTrackjs.ts` file. The change modifies the `version` property to include an additional fallback value from the environment variables.
* [`src/hooks/useTrackjs.ts`](diffhunk://#diff-a3c338371e016a85f1439b68696461946c57ff2fa5003033e90d48390d3a4d04L20-R23): Updated the `version` property to use `process?.env?.REF_NAME` as an additional fallback if the meta tag is not found.
> fix: add version for trackjs

- src/external/bot-skeleton/scratch/blocks/Binary/Before Purchase/before_purchase.js
- src/external/bot-skeleton/scratch/blocks/Binary/Before Purchase/purchase.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_accumulator.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_candleinterval.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_contracttype.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_market.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_multiplier.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_restartbuysell.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_restartonerror.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js
- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradetype.js
This pull request includes multiple changes to the `trade_definition` files in the `bot-skeleton` directory. The primary aim is to enhance the context menu functionality by excluding specific options.
Added method to remove the disable option on the trade parameter child blocks.
> fix: removed disable option in trade parameters blocks

- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js
This pull request includes changes to the `trade_definition_tradeoptions` block in the `src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_tradeoptions.js` file. The changes add checks for unsupported trade types and ensure that the minimum stake value is set correctly for certain currency blocks.
Key changes:
* Added a check to exclude unsupported trade types 'multiplier' and 'accumulator' from processing.
* Introduced additional checks to ensure that `currency_block` and `currency_child_block` exist before proceeding.
* Set the value of `currency_child_block` to the minimum stake when both `currency_block` and `currency_child_block` are present.
> chore: update default stake on trade parameter upon account switch

- vercel.dr.json
Fixed vercel.json for SPA routing configuration
Added `vercel.json` to handle client-side routing in our Single Page Application (SPA) when deployed to Vercel. This configuration ensures that all routes are properly handled and prevents 404 errors when accessing paths directly or refreshing pages.
- Modified vercel.dr.json to include both build settings and SPA routing configuration
- Used rewrites instead of routes for better compatibility
- Removed cleanUrls as it was causing 404 errors on subpages when combined with rewrites
> fix vercel dr publish

- src/app/App.tsx
- src/components/layout/header/account-switcher.tsx
- src/components/layout/header/platform-switcher/platform-switcher.tsx
[App Separation] - Integrate query param logic to maintain auth context propagation
Description: As a developer I want to implement a seamless auth flow. Meaning if the user clicks on DBot from [app.deriv.com](http://app.deriv.com/) (Traders Hub/Dtrader) or any other app. It should propagate the selected account in the source tab to the newly opened tab.
Slack Conversation: https://deriv-group.slack.com/archives/C0871BRSJN4/p1735032395607869 
Scenarios Document: https://docs.google.com/document/d/1Taq5ypnVG8KDVWTx5IdPJyWRaB3PCaNXa2yEVOMddNA/edit?usp=sharing 
[DBOT] Account Switching Across Tabs
We need to standardise the behaviour of the platforms/tabs being opened from the TH and vice versa. Due to different standalone applications - Bots, P2P, Dtrader and TH the behaviour varies across …
> maryia/BOT-2661/[App Separation] - Integrate query param logic to maintain auth context propagation

- src/stores/client-store.ts
This pull request includes a small change to the `ClientStore` class in the `src/stores/client-store.ts` file. The change ensures that the `clientAccounts` item is also removed from local storage when clearing user data.
* [`src/stores/client-store.ts`](diffhunk://#diff-9871fceff588cf0886088bfb95115a7c98e9dda049ebdd6f58ccb86836019e89R311): Added removal of `clientAccounts` from local storage in the `ClientStore` class.
> chore: remove clientAccounts on logout

- src/external/bot-skeleton/services/api/api-base.ts
This pull request includes a small but important change to the `src/external/bot-skeleton/services/api/api-base.ts` file. The change adds a condition to check for an active token before setting the `active_symbols_promise`.
* [`src/external/bot-skeleton/services/api/api-base.ts`](diffhunk://#diff-3b0931891357dd6358fa53dcd1ab528d4de6ec5e344c41956adbe694df9e4c89L103-R103): Modified the condition to check for an active token using `V2GetActiveToken()` before setting `active_symbols_promise`.
> fix: active symbol call sequence after authorize

- src/app/App.tsx
- src/app/AuthWrapper.tsx
- src/components/shared/utils/config/config.ts
- src/components/shared/utils/routes/routes.ts
- src/main.tsx
- src/pages/callback/callback-page.tsx
This pull request includes several changes to the authentication flow and the initialization process in the application. The most important changes involve the refactoring of the login information handling, the introduction of an `AuthWrapper` component, and modifications to the `CallbackPage` component.
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L2-R2): Removed the login information handling logic and the use of `Fragment` in the `App` component. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L2-R2) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L12) [[3]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L52-L82) …
> fix: default currency

- src/app/App.tsx
- src/pages/callback/callback-page.tsx
This pull request includes changes to improve the handling of user login IDs by utilizing cookies in addition to local storage. The most important changes involve importing the `js-cookie` library and updating the logic to read and log user login IDs from cookies.
Enhancements to user login ID handling:
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R4): Imported `js-cookie` and updated the `useEffect` hook to read `active_loginid` from cookies, falling back to local storage if necessary. Added a console log for debugging purposes. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R4) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L74-R82)
* …
> fix: added cookies to fix silent login

- src/app/App.tsx
This pull request includes changes to the `src/app/App.tsx` file to improve the handling of client accounts stored in cookies and local storage. The most important changes include adding validation for the format of `cookie_accounts`, updating the storage logic for `accounts_list`, and ensuring consistent storage updates.
Improvements to client accounts handling:
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L73-R88): Added validation to check if `cookie_accounts` is an array and log an error if the format is invalid.
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L73-R88): Updated the storage logic to combine `accounts_list` and `cookie_accounts`, ensuring that `accounts_list` …
> fix: silent login

- src/app/App.tsx
This pull request includes changes to the `src/app/App.tsx` file, primarily commenting out the `updateAccountParamInURL` function and its calls. This function was responsible for updating the account parameter in the URL based on the account data.
Changes to `src/app/App.tsx`:
* Commented out the `updateAccountParamInURL` function definition, which was used to update the URL with account parameters.
* Commented out the calls to `updateAccountParamInURL` in three different places within the `App` function. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L88-R88) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L145-R145)
> fix: fix search param check

- src/components/layout/index.tsx
- src/pages/callback/callback-page.tsx
This pull request includes several changes to the `Layout` component and the `CallbackPage` component to improve currency validation and user redirection. The most important changes include adding state management for client currency, refactoring currency validation logic, and updating the redirection logic on the callback page.
Improvements to currency validation and state management:
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL32-R32): Added `setClientHasCurrency` to the state management for client currency.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL43-R57): Refactored the currency validation logic to use a `Set` for checking if all …
> fix: oauth route after the callback

- src/components/layout/index.tsx
- src/pages/callback/callback-page.tsx
This pull request focuses on changing the storage mechanism for currency-related data from `localStorage` to `sessionStorage` in the `src/components/layout/index.tsx` and `src/pages/callback/callback-page.tsx` files. The key changes include updating how currency data is stored and retrieved, ensuring that the session-specific data is used instead of data that persists across sessions.
Changes to storage mechanism:
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL47-R47): Replaced `localStorage` with `sessionStorage` for setting and removing the `query_param_currency`. [[1]](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL47-R47) …
> Rupato/fix  OIDC  query param

- src/external/bot-skeleton/scratch/utils/index.js
This pull request includes significant changes to the `getDisabledBlocks` function in the `src/external/bot-skeleton/scratch/utils/index.js` file. The changes enhance the logic for identifying disabled blocks by incorporating a list of required block types and checking for mandatory blocks.
Key changes include:
* [`src/external/bot-skeleton/scratch/utils/index.js`](diffhunk://#diff-02a1baf8cbe6106e718d189be9fd8018e21b9ff729131f27aedfa85724803c04L407-R421): Refactored the `getDisabledBlocks` function to use the `workspace` and `required_block_types` parameters to identify and flag disabled blocks. This includes checking for mandatory blocks and filtering based on their disabled status.
> Rupato/Fix Blockly mandatory block error

- .github/workflows/build-and-deploy-test.yml
This pull request includes a small change to the `.github/workflows/build-and-deploy-test.yml` file. The change updates the `actions/cache/restore` action to a new version.
* [`.github/workflows/build-and-deploy-test.yml`](diffhunk://#diff-d63278f79551d70a0ecc23a55e3dc2e84fbd33ca883e2eed36768ae27c245fa5L68-R68): Updated `actions/cache/restore` action from `e12d46a63a90f2fae62d114769bbf2a179198b5c` to `d4323d4df104b026a6aa633fdb11d772146be0bf`.
> fix: updated sha

- package-lock.json
- package.json
This pull request includes updates to the `package.json` file to add support for various embedded Sass versions. The most important changes are the addition of the `sass-embedded` package and several optional dependencies for different platforms.
Dependency updates:
* Added `sass-embedded` version `^1.85.1` to the dependencies section.
* Added multiple `sass-embedded` versions for different platforms to the optional dependencies section.
> fix: added sass-embedded as optional dependencies

- src/components/layout/index.tsx
This pull request includes a small change to the `src/components/layout/index.tsx` file. The change removes the line that updates the browser history with the session storage currency parameter.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL70-L71): Removed the line that updates the browser history with the session storage currency parameter.
> fix: oidc issues

- src/app/CoreStoreProvider.tsx
- src/hooks/auth/useOauth2.ts
This pull request includes changes to ensure that the `query_param_currency` is removed from `sessionStorage` upon logging out. This update affects both the `CoreStoreProvider` component and the `useOauth2` hook.
Changes to session storage management:
* [`src/app/CoreStoreProvider.tsx`](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8R108-R110): Added logic to remove `query_param_currency` from `sessionStorage` during the OAuth logout process.
* [`src/hooks/auth/useOauth2.ts`](diffhunk://#diff-7ed7d4a03c35423f9e58a16d28f0b5af98eee2e3f4e729a311f562cd8b5d268bR45-R47): Added logic to remove `query_param_currency` from `sessionStorage` in the `logoutHandler` function.
> fix: remove query param on logout

- src/components/layout/index.tsx
This pull request includes a small change to the `src/components/layout/index.tsx` file. The change involves moving the `sessionStorage.setItem('query_param_currency', currency);` line to a different position within the conditional block. 
This adjustment ensures that the `query_param_currency` is set in the session storage before it is retrieved and used, which could help avoid potential issues with undefined or incorrect values.
> fix: first login

- src/utils/traders-hub-redirect.ts
This pull request includes updates to the `src/utils/traders-hub-redirect.ts` file to enhance URL redirection logic for the Trader's Hub. The changes focus on refining the URL construction and parameter handling for different product types and account values.
Key changes include:
* Updated `getTraderHubUrl` function to map `product_type` to a `redirect_to` parameter and construct the redirect URL accordingly.
* Modified the URL construction in `getWalletUrl` function to use the new redirect pattern with `redirect_to=wallet`.
* Refined the handling of the `account` parameter to determine the account value based on whether it is a demo or a specific currency. This change applies to both `getTraderHubUrl` and `getWalletUrl` functions. …
> BOT-2714/Rupato/fix--query params on redirection

- src/app/App.tsx
- src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet-item.tsx
- src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet.tsx
- src/components/layout/index.tsx
- src/components/shared_ui/input/input.tsx
- src/pages/callback/callback-page.tsx
- src/utils/traders-hub-redirect.ts
This pull request includes several updates to the `src/app` and `src/components` directories, mainly focusing on re-enabling previously commented-out functions, adding checks for missing tokens, and removing console logs.
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L62-R69): Re-enabled the `updateAccountParamInURL` function and its calls in various parts of the `App` function. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L62-R69) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L88-R88) [[3]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L145-R145)
* [`src/components/layout/header/AccountSwitcherWallet/account-switcher …
> fix: OIDC login issue

- src/stores/run-panel-store.ts
This pull request includes a modification to the `RunPanelStore` class in `src/stores/run-panel-store.ts` to improve the handling of bot stop notifications. The primary change involves refactoring the `setShowBotStopMessage` method for better readability and functionality.
Key changes:
* [`src/stores/run-panel-store.ts`](diffhunk://#diff-896fc35ee731169d31b53e8b911d8fd8b93d382a639ea1a3967ba325e0a251e8L144-R162): Refactored the `setShowBotStopMessage` method to introduce a new function `handleNotificationClick` for improved readability and added logic to handle query parameters for the account.
> fix: added for toast notification

- src/components/layout/header/header.tsx
- src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request includes changes to enhance URL handling by adding account parameters based on the account type (demo or real) and currency. The changes are implemented in both the desktop and mobile menu configurations.
Enhancements to URL handling:
* [`src/components/layout/header/header.tsx`](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L45-R67): Modified the `AppHeader` component to dynamically set the account parameter in the URL for account settings based on whether the account is a demo or real account.
* [`src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx`](diffhunk://#diff-d1dbf017cbc6be00aadfd73ef141a2bfdf9f90b8464e96f24ae4f7870bdf6477R54-R74): Added a `getAccountUrl` function to append the account parameter to URLs and …
> fix: redirection on account profile

- src/components/shared_ui/input/input.tsx
This pull request includes a change to the `src/components/shared_ui/input/input.tsx` file to improve input handling for specific cases. The most important change ensures that the `tick_count` input field does not accept decimal values and that other input fields are limited to two decimal places.
Input handling improvements:
* [`src/components/shared_ui/input/input.tsx`](diffhunk://#diff-d4452a71213ae40d6e266e462d79b99dcac609117a62fea908ac2573e52060d2L106-R123): Added special handling for the `tick_count` input field to prevent decimal input entirely and limited other input fields to two decimal places.
> fix: the input fields

- src/components/shared_ui/contract-card/contract-card-items/contract-card-header.tsx
- src/components/shared_ui/contract-card/contract-card-items/tick-counter-bar.tsx
This pull request includes changes to simplify the `TickCounterBar` component and its usage in the `ContractCardHeader` component by removing the `max_ticks_duration` property.
Simplification of `TickCounterBar` component:
* [`src/components/shared_ui/contract-card/contract-card-items/tick-counter-bar.tsx`](diffhunk://#diff-542f357a5df96224006f321a8261ebf621f800d7ae6a12b51d1239ca5b3258b5L7-R12): Removed the `max_ticks_duration` property from the `TTickCounterBar` type and the `TickCounterBar` component. Updated the displayed text to exclude `max_ticks_duration`.
Usage updates in `ContractCardHeader` component:
* [`src/components/shared_ui/contract-card/contract-card-items/contract-card-header.tsx`](diffhunk://#diff-b3c61714a88e9337cb3c53e07aa67d1fa4403de82014f686263dd1759bf37169L171-R171): …
> fix: Fix--to-remove-the-accoumulator-ticks

- src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx
This pull request includes a small change to the `src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx` file. The change ensures that the `tick_count` input field only accepts numeric values.
* [`src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx`](diffhunk://#diff-a5d6442de8ce7ac0e7af26611c486cceb1e7537c2a57284449af9a42f88802e2R149-R159): Added `inputMode`, `pattern`, and `onKeyPress` properties to restrict `tick_count` input to numeric values only.
> fix: decimal digit

- src/pages/bot-builder/quick-strategy/config.ts
- src/pages/bot-builder/quick-strategy/form.tsx
- src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx
- src/pages/bot-builder/quick-strategy/selects/growth-rate-type.tsx
- src/pages/bot-builder/quick-strategy/types.ts
This pull request includes several changes to the `quick-strategy` feature in the bot builder, focusing on input validation and error handling improvements. The most important changes include adding integer validation to the duration field, updating the input handling for stake and max_stake fields, and enhancing error message display logic.
Input validation improvements:
* [`src/pages/bot-builder/quick-strategy/config.ts`](diffhunk://#diff-69713ed61ab92a04940214bde8f1d48d6400960345e1ddd24e61a7618c63186eL190-R190): Added 'integer' to the validation array for the duration field to ensure only integer values are accepted.
* [`src/pages/bot-builder/quick-strategy/types.ts`](diffhunk://#diff-9e0f3ec8da20e27627e82113e3121399fedadd48b2e6c772dd4b44fd0dcc747bL14-R27): Added a new validation type …
> fix: qs bugs

- src/external/bot-skeleton/scratch/utils/index.js
- src/stores/google-drive-store.ts
fix: removed notification from gdrive handler and added message to skeleton when parsing succeeds
> Moiz-BOT-2736-Remove dual notifications generation when importing from GDrive

- src/app/App.tsx
- src/app/AuthWrapper.tsx
- src/external/bot-skeleton/services/api/api-base.ts
- src/external/bot-skeleton/services/api/chart-api.js
- src/hooks/auth/useOauth2.ts
- src/hooks/useInvalidTokenHandler.ts
- src/pages/callback/callback-page.tsx
This pull request introduces a mechanism to handle invalid tokens by retriggering OIDC authentication when an invalid token is detected and the logged state cookie is true. The changes span multiple files and involve importing necessary modules, adding event listeners, and updating the logic to emit and handle the 'InvalidToken' event.
Key changes include:
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R7): Integrated `useInvalidTokenHandler` hook to handle invalid tokens and ensure proper cleanup on component unmount. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R7) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R52-R62)
* …
> Rupato/fix: the invalid token handler

- src/pages/callback/callback-page.tsx
This pull request includes a small change to the `src/pages/callback/callback-page.tsx` file. The change modifies the method used for redirecting the user after ensuring the currency is included in the URL.
* [`src/pages/callback/callback-page.tsx`](diffhunk://#diff-48442a2313eb74f85495b7177c68f5054c9518faf6198893217e053cb9a7b836L74-R74): Changed `window.location.assign` to `window.location.replace` to redirect the user.
> fix: OIDC browser back button issue

- src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_market.js
- src/stores/dashboard-store.ts
fix: Synced symbol selection between bot builder and charts tab
> Moiz-BOT-2742-Sync Deriv Bot Asset Display in Charting Functionality

- src/hooks/useInvalidTokenHandler.ts
This pull request updates the `useInvalidTokenHandler` hook to improve its handling of invalid tokens by ensuring local storage is cleared before retriggering the OAuth2 login.
Improvements to token handling:
* [`src/hooks/useInvalidTokenHandler.ts`](diffhunk://#diff-8605e1cbcded6bbc6ae855bc9989448fd87174d7b411203bee33a57b871e6618R19-R24): Added logic to clear specific items from `localStorage` (`active_loginid`, `accountsList`, `authToken`, and `clientAccounts`) in the `handleInvalidToken` function to ensure a clean state before calling `retriggerOAuth2Login`.
> fix: dbot logout issue

- src/external/bot-skeleton/services/api/chart-api.js
This pull request includes a small but important change to the `ChartAPI` class in the `chart-api.js` file. The change ensures that specific local storage items are cleared when an error occurs during chart API authorization.
Key change:
* [`src/external/bot-skeleton/services/api/chart-api.js`](diffhunk://#diff-ee46996129ef95e20f0222c7e4286fbf0e50b616b207768454403b9704e174daR29-R32): Added removal of `active_loginid`, `accountsList`, `authToken`, and `clientAccounts` from local storage in the error-handling block of the `ChartAPI` class. This helps maintain a clean state in case of authorization errors.
> fix: chart load issue

- src/app/App.tsx
This pull request removes the `useInvalidTokenHandler` hook from the `App` component in `src/app/App.tsx`, simplifying the component by eliminating unused functionality.
Code cleanup:
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L7): Removed the import for `useInvalidTokenHandler` and its associated code, including the `unregisterHandler` cleanup logic in the `App` component. This streamlines the component by removing unused code. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L7) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L52) [[3]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L61-L62)
> fix: unregisterHandler

- src/components/tnc-status-update-modal/tnc-status-update-modal.tsx
- src/pages/dashboard/info-panel.tsx
- src/pages/tutorials/dbot-tours/common/tour-start-dialog.tsx
- src/stores/client-store.ts
fix: removed modal overlap caused due to rendering of both tnc and welcome tour modal simultaneously.
Condition check added if welcome popup is open then the TNC popup will not render in
> Moiz- BOT-2689 - Popup and Welcome to Deriv Bot Popup overlaping each other

- src/external/bot-skeleton/services/api/api-base.ts
- src/utils/index.ts
This pull request introduces error-handling improvements in the API service and updates a utility function to expand domain validation. The most important changes are detailed below.
* Enhanced the error-handling logic in `APIBase` to wrap the existing error-checking code in a `try-catch` block. This ensures that any unexpected errors during error handling itself are caught, logged to the console, and handled gracefully by clearing authentication data and setting `isAuthorizing` to `false`. (`src/external/bot-skeleton/services/api/api-base.ts`, [src/external/bot-skeleton/services/api/api-base.tsL169-R187](diffhunk://#diff-3b0931891357dd6358fa53dcd1ab528d4de6ec5e344c41956adbe694df9e4c89L169-R187))
* Updated the `isDotComSite` utility function to include `.be` and `.me` domains in addition …
> fix: invalid token

- src/constants/contract.ts
> Moiz-BOT-2789-Rise/fall trade type is not shown on run panel

- src/components/shared/utils/routes/routes.ts
This pull request introduces support for a new service, `derivHub`, by extending the `Service` type, updating domain configurations, and dynamically generating URLs for the new service. The changes improve modularity and maintainability by centralizing domain management and URL generation.
* **Added `derivHub` to the `Service` type**: The `Service` type now includes `derivHub` to represent the new service. (`[src/components/shared/utils/routes/routes.tsL1-R1](diffhunk://#diff-ae17cb6ca59eef476b8070e4acb7af4aa4beee209c84f7f87d1b4212f62a8a6aL1-R1)`)
* **Updated domain configurations**: Added staging and production domain URLs for `derivHub` in the `domains` object. (`[src/components/shared/utils/routes/routes.tsR38-R45](diffhunk://#diff-ae17cb6ca59eef476b8070e4acb7af4aa4beee209c84f7f87d1b421 …
> fix: deriv hub check

- src/components/layout/header/account-switcher.tsx
- src/components/layout/header/common/real-accounts.tsx
- src/components/layout/header/common/types.tsx
- src/components/layout/header/header.tsx
- src/components/layout/header/menu-items/menu-items.tsx
- src/components/shared/utils/routes/routes.ts
- src/utils/traders-hub-redirect.ts
This pull request includes updates to improve the handling of account-related logic, streamline routing, and integrate GrowthBook feature flags. The most important changes include modifying the `upgradeable_landing_companies` structure, updating route definitions, and refactoring GrowthBook usage for feature flag checks.
* Changed the structure of `upgradeable_landing_companies` from an array to a string in `TRealAccounts` and updated related logic in `real-accounts.tsx` and `account-switcher.tsx` to reflect this change. [[1]](diffhunk://#diff-bf3f2df057110808659b78456c70e733dec577bee954e3fc8391016c313164d1L80-R80) [[2]](diffhunk://#diff-4de4e43d901612b973866c07cad955bf91f25d95a235e111d1dcd15b39edcbeeL25-R29) [[3]](diffhunk://#diff-4de4e43d901612b973866c07cad955bf91f25d95a235e111d1dcd15b39 …
> fix: dbot bug fixes

- src/pages/tutorials/dbot-tours/common/tour-start-dialog.tsx
This pull request includes a minor update to the `TourStartDialog` component in the `src/pages/tutorials/dbot-tours/common/tour-start-dialog.tsx` file. The change simplifies the localized text displayed to users and removes an unused redundant localization block.
Changes to `TourStartDialog`:
* Simplified the `i18n_default_text` to remove the line break and redundant phrasing, making the message more concise.
* Removed an unused `Localize` block that contained a placeholder message (`Hello World`).
> fix: translations

- src/components/shared/utils/url/helpers.ts
- src/utils/traders-hub-redirect.ts
This pull request updates the logic for determining platform URLs and simplifies the `getBaseTraderHubUrl` function by removing dependencies on external constants and helper functions. The changes primarily focus on improving maintainability and aligning URL patterns with the application's requirements.
* [`src/components/shared/utils/url/helpers.ts`](diffhunk://#diff-f94a2b43d9e9ace3e25aff62ca99c4b0840505637c5a2648fbfc041574cf991fL23-R24): Updated the regular expressions in `getPlatformFromUrl` to reflect the new URL patterns for `staging-dbot` and `dbot` subdomains instead of `staging-app` and `app`.
* [`src/utils/traders-hub-redirect.ts`](diffhunk://#diff-9e7ebbfc33380b8cdf202af9e5245d86a38c208dc40653c168d120e0d4dd8100L2-R21): Refactored `getBaseTraderHubUrl` to directly use …
> Fix  staging url

- src/components/shared_ui/autocomplete/autocomplete.tsx
fix: added binding of active index based on value passed
> Moiz - BOT-2777 - On the initial load, when an asset is clicked, the selected asset is not highlighted in the dropdown list.

- src/components/layout/header/header.tsx
- src/components/layout/index.tsx
- src/hooks/auth/useOauth2.ts
- src/utils/index.ts
This pull request removes the `isDotComSite` utility function and its usage across the codebase, simplifying the logic for authentication and site checks. The most important changes include the removal of the `isDotComSite` function, updates to authentication logic in several components and hooks, and the cleanup of unused imports.
* [`src/utils/index.ts`](diffhunk://#diff-6147e3c1761df71fd40952dbcbac388a45f80b8c318f367ef41048351a2c0c99L4-L11): Deleted the `isDotComSite` function, which checked if the current site was a `.com`, `.be`, `.me` domain, or localhost.
* [`src/components/layout/header/header.tsx`](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L15): Removed the conditional check for `isDotComSite` before calling `requestOidcAuthentication` in …
> fix: removed the dotcom check

- src/components/layout/header/header.tsx
- src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request introduces changes to the header and mobile menu components to improve the handling of redirect URLs and conditional menu items based on user account type and country-specific feature flags. The most important changes include adding logic to determine if a user's country is in a hub-enabled list and updating the behavior of redirects and menu configurations accordingly.
* Updated the `AppHeader` component to dynamically set the `redirect_url` based on whether the user has a wallet and resides in a hub-enabled country. This ensures that users in eligible countries are redirected to the appropriate settings page.
* Refactored the `useMobileMenuConfig` hook to move the `is_hub_enabled_country` calculation outside of the `getRedirectUrl` function for better readability and …
> Rupato/fix: cashier link

- src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request modifies the behavior of the mobile menu configuration in `use-mobile-menu-config.tsx` to adjust the visibility of the "Cashier" menu item based on wallet and country hub settings.
* [`src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx`](diffhunk://#diff-d1dbf017cbc6be00aadfd73ef141a2bfdf9f90b8464e96f24ae4f7870bdf6477L130-R131): Updated the condition for displaying the "Cashier" menu item. The menu item is now shown when the user does **not** have a wallet and is **not** in a hub-enabled country, instead of the previous condition that required both to be true.
> fix: cashier link

- src/app/app-root.tsx
This pull request removes the `TradingAssesmentModal` component from the `AppRoot` component in `src/app/app-root.tsx`. This change simplifies the structure of the application by eliminating an unused or unnecessary component.
* [`src/app/app-root.tsx`](diffhunk://#diff-94879295562881d6d113d5d186e88ce8f3e5357139e22d4d8b73b250914133a8L6): Removed the import of `TradingAssesmentModal` and its usage within the `AppRoot` component. [[1]](diffhunk://#diff-94879295562881d6d113d5d186e88ce8f3e5357139e22d4d8b73b250914133a8L6) [[2]](diffhunk://#diff-94879295562881d6d113d5d186e88ce8f3e5357139e22d4d8b73b250914133a8L67)
> fix: removed trading assesment modal

- src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx
- src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet.tsx
- src/components/layout/header/header.scss
- set Trader's Hub CTA text color to black
- `npm test` *(fails: jest not found)*
> Matin/Fix Trader's Hub CTA color

- src/hooks/useTMB.ts
This pull request includes a small change to the `useTMB` hook in `src/hooks/useTMB.ts`. The change ensures that the `is_tmb_enabled` value is stored in `localStorage` for consistent access across non-React components.
> fix: added localstorage check

- src/app/AuthWrapper.tsx
- src/components/layout/header/header.tsx
- src/external/bot-skeleton/services/api/api-base.ts
- src/hooks/useTMB.ts
- src/stores/app-store.ts
This pull request refactors how the `is_tmb_enabled` flag is handled across the codebase. The flag, which was previously stored in `localStorage`, is now stored in the global `window` object. This change ensures consistent access to the flag across all components and simplifies its management. The most important changes include updating the logic for accessing `is_tmb_enabled`, modifying its initialization, and extending the `Window` interface.
* **Global storage for `is_tmb_enabled`:** The `is_tmb_enabled` flag has been moved from `localStorage` to the global `window` object. This change ensures all components access the flag consistently using `window.is_tmb_enabled`. (`[[1]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aL44-R51)`, …
> fix: remove localstorage value and use firebase config

- src/hooks/useTMB.ts
This pull request modifies the `useTMB` hook in `src/hooks/useTMB.ts` to enhance how the `is_tmb_enabled` value is stored and accessed across components. The changes ensure that the value is first retrieved from `localStorage` (if available) before falling back to the computed value.
Key changes in `useTMB`:
* Updated the logic for setting `window.is_tmb_enabled` to prioritize retrieving the value from `localStorage`. If a stored value exists, it is parsed using `JSON.parse`; otherwise, the computed `isEnabled` value is used. [[1]](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L68-R69) [[2]](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L78-R80)
> fix: local storage valuer

- src/components/layout/header/header.tsx
- src/hooks/useTMB.ts
This pull request introduces several debug logs across the codebase to provide more visibility into the values of key variables related to TMB (Trading Management Bot) functionality. These logs are intended for debugging purposes and should be reviewed for potential removal or refinement before merging into production.
* [`src/components/layout/header/header.tsx`](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3R136-R137): Added a console log to display the value of `is_tmb_enabled` during the `query_param_currency` processing.
* `src/hooks/useTMB.ts`: 
- Added a console log to show the `result` from the API and the value of `window.is_tmb_enabled` after parsing the stored value from `localStorage`.
- Added a detailed console log to output the state of …
> fix: check tmb consoles

- src/app/CoreStoreProvider.tsx
This pull request introduces a new hook, `useTMB`, to enhance the functionality of the `CoreStoreProvider` component. The most important changes involve integrating this hook to determine the `is_tmb_enabled` state and updating the logic for handling the `isLoggedOutCookie` condition.
* [`src/app/CoreStoreProvider.tsx`](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8R11): Added import for `useTMB` to utilize its functionality within the `CoreStoreProvider` component.
* [`src/app/CoreStoreProvider.tsx`](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8L27-R35): Introduced a new `is_tmb_enabled` state using `useTMB` and `useMemo` to combine the hook's output with a global `window.is_tmb_enabled` flag. This state is used to …
> fix: account switcher currency names

- src/hooks/useTMB.ts
This pull request updates the `useTMB` hook to handle additional cases for localStorage values, ensuring more robust behavior when determining the `is_tmb_enabled` status.
Enhancements to localStorage value handling:
* [`src/hooks/useTMB.ts`](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L118-R128): Modified the logic to explicitly handle both `'true'` and `'false'` values from localStorage, ensuring that the `is_tmb_enabled` status is correctly set and the determination process is finalized in both cases. [[1]](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L118-R128) [[2]](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L147-R162)
> fix: localstorage check for tmb

- src/hooks/useTMB.ts
This pull request introduces a small but important enhancement to the `useTMB` hook. It adds support for handling a special `accountParam` value of `'demo'` by selecting a token with a login ID containing `'VR'`.
* **Enhanced token selection logic in `useTMB`**: Added a condition to check if `accountParam` is `'demo'`. If true, the hook now selects a token with a login ID containing `'VR'` from the `activeSessions.tokens` array. This improves flexibility in handling demo accounts. (`[src/hooks/useTMB.tsR331-R346](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958R331-R346)`)
> fix: tmb check for the demo account

- .github/workflows/build-and-deploy-production.yml
- .github/workflows/build-and-deploy-staging.yml
- .github/workflows/sync-translations.yml
This pull request updates the GitHub Actions workflows to explicitly set `permissions` for the `contents` scope to `read`. This change enhances security by adhering to the principle of least privilege, ensuring that workflows only have the permissions they need.
* [`.github/workflows/build-and-deploy-production.yml`](diffhunk://#diff-d8dfcbc7adf0e8cc7010e2eb020a5be671e7fed87aa32446ae7ef0e66fc1bfcaR17-R18): Added `permissions: contents: read` to the `jobs` section for the production deployment workflow.
* [`.github/workflows/build-and-deploy-staging.yml`](diffhunk://#diff-b709f2739a5258d6c2c45e190ddc8e9329c2492822f44b593a8de5145e930b42R17-R18): Added `permissions: contents: read` to the `jobs` section for the staging deployment workflow.
* …
> Rupato/fix: codeQL workflows

- src/app/CoreStoreProvider.tsx
This pull request introduces a change to the `CoreStoreProvider` component in `src/app/CoreStoreProvider.tsx` to ensure cookies are set with the appropriate domain. The key updates involve calculating the current domain dynamically and using it when setting cookies.
**Enhancements to Cookie Management:**
* Added a `currentDomain` variable using `useMemo` to dynamically calculate the domain based on the current hostname (`src/app/CoreStoreProvider.tsx`, [src/app/CoreStoreProvider.tsxR27](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8R27)).
* Updated the `Cookies.set` function to include the `domain` option, ensuring cookies are scoped to the calculated domain (`src/app/CoreStoreProvider.tsx`, [src/app/CoreStoreProvider.tsxL184-R187](diffhunk://#diff-5ec796 …
> fix: domain cookie domain name

- src/stores/self-exclusion-store.ts
This pull request updates the error handling and type definitions in the `SelfExclusionStore` class to improve type safety and handle specific authorization errors gracefully.
* Updated the `getSelfExclusion` response to include a type definition for `get_self_exclusion` with an optional `max_losses` property. (`[src/stores/self-exclusion-store.tsL70-R80](diffhunk://#diff-172218cfc4b84f2c01b16f2169441e3b8273810e60eec63bf7e4e76387dbd1cfL70-R80)`)
* Enhanced the `.catch` block to handle errors with a specific structure, checking for an `AuthorizationRequired` error code. If encountered, the client is logged out before logging the error. (`[src/stores/self-exclusion-store.tsL70-R80](diffhunk://#diff-172218cfc4b84f2c01b16f2169441e3b8273810e60eec63bf7e4e76387dbd1cfL70-R80)`)
> fix: authorization error on self exclusion

- src/components/shared/utils/config/config.ts
- src/components/shared/utils/login/login.ts
This pull request introduces changes to improve the handling of OAuth URLs by dynamically determining the appropriate domain based on the current production environment. The updates ensure better compatibility with different environments and enhance the flexibility of the OAuth URL generation.
* **Dynamic domain handling in `generateOAuthURL`:** Added logic to replace the hostname with a dynamically determined OAuth domain suffix if the original hostname includes `oauth.deriv.`. This ensures the OAuth URL aligns with the current production domain. (`src/components/shared/utils/config/config.ts`)
* **Refactor in `loginUrl` function:** Updated the OAuth URL generation to use a dynamic domain (`getCurrentProductionDomain`) as a fallback to the default hostname, improving adaptability across …
> fix: domain generation for oauth

- src/components/shared/utils/login/login.ts
This pull request introduces updates to the `loginUrl` function in `src/components/shared/utils/login/login.ts`, primarily to enhance domain handling logic and add debugging logs. The changes aim to ensure the correct OAuth domain is constructed dynamically based on the current production domain.
* Updated the logic to extract the domain suffix (e.g., `'deriv.me'` from `'dbot.deriv.me'`) when a current production domain is detected, and dynamically set the OAuth domain accordingly.
* Added multiple `console.log` statements to log the current domain, OAuth domain, and constructed URLs at various stages for debugging purposes.
> Rupato/fix  dot me be

- src/components/shared/utils/config/config.ts
- src/hooks/useTMB.ts
This pull request adds support for a new server URL, `canary.derivws.com`, in two locations within the codebase. The change ensures that the new server URL is considered valid when determining server configurations.
* [`src/components/shared/utils/config/config.ts`](diffhunk://#diff-49f2fb91bde2f51d34f95f726562ff893ed6f51557b764366c63997105a3043cL155-R155): Added `canary.derivws.com` to the `valid_server_urls` array in the `generateOAuthURL` function.
* [`src/hooks/useTMB.ts`](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L74-R79): Added `canary.derivws.com` to the `valid_server_urls` array in the `useTMB` hook.
> fix: added canary server url

- src/components/shared/utils/browser/browser_detect.ts
- src/pages/dashboard/announcements/announcements.tsx
- src/utils/pwa-utils.ts
This pull request introduces improved browser detection utilities and updates the logic for displaying PWA-related announcements and modals, especially to better handle unsupported browsers like Safari Desktop and Firefox. The main goal is to prevent users on these browsers from seeing PWA installation prompts or announcements, as their support for PWA is limited or non-existent.
**Browser detection utilities:**
* Added `isFirefox` and improved usage of `isSafari` in `browser_detect.ts` to help identify unsupported browsers for PWA features.
* Updated imports and usage of these utilities in relevant files, such as `announcements.tsx` and `pwa-utils.ts`. [[1]](diffhunk://#diff-2fcabe876577ab0939c5a73c6e5f95eb78e51721fa37d75a78abe50c6775f416R5) …
> fix: remove pwa from firefox and safari browsers

- src/pages/dashboard/announcements/config.tsx
This pull request makes a minor update to the `BOT_ANNOUNCEMENTS_LIST` in `config.tsx`, changing the date of an announcement.
* Changed the `date` field for the "Install Deriv Bot as an App" announcement from '29 January 2025' to '28 August 2025'.
> fix: pwa announcement date

- src/main.tsx
- src/pages/dashboard/announcements/announcements.tsx
- src/utils/pwa-utils.ts
This pull request restricts PWA (Progressive Web App) support exclusively to Chrome browsers, updating both the logic and user-facing elements to reflect this change. The code now checks for Chrome specifically, disables PWA features on all other browsers (including Safari and Firefox), and updates related user interface logic and event tracking accordingly.
**PWA Support Restriction to Chrome:**
- Updated the service worker registration logic in `pwa-utils.ts` to only enable registration on Chrome browsers, with improved logging and early returns for unsupported browsers.
- Modified the function `isUnsupportedPWABrowser` to return `true` for any non-Chrome browser, and added a new utility `isChromeOnlyPWA` for Chrome detection.
- Adjusted the logic in `shouldShowPWAModal` to only show …
> fix: chrome safari and firefox

- src/analytics/rudderstack-common-events.ts
This pull request makes a minor update to the analytics event tracking for PWA installs. The change updates the event properties to use `subform_name` and `subform_source` instead of the previous `subpage_name`, and sets their values accordingly.
- Updated the `rudderStackSendPWAInstallEvent` function in `src/analytics/rudderstack-common-events.ts` to replace the `subpage_name` property with `subform_name` and `subform_source` when tracking the PWA install event.
> fix: rudderstack event for pwa

- src/pages/dashboard/announcements/utils/accumulator-helper-functions.ts
This pull request enhances analytics tracking for PWA-related announcements in the dashboard by integrating RudderStack event tracking into the announcement utilities. The most important changes are:
**Analytics Integration:**
* Imported `rudderStackSendPWAInstallEvent` and `rudderStackSendAnnouncementClickEvent` from the appropriate analytics modules into `accumulator-helper-functions.ts` to enable event tracking for announcement interactions.
**Event Tracking on PWA Announcement:**
* Updated the `performButtonAction` function to send an announcement click event and a PWA install event to RudderStack when the PWA install announcement is triggered, improving observability of user interactions with PWA-related announcements.
> fix: announcement name for pwa trigger
