deriv-com/bot

.github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml
- Removed permission from build-and-deploy-test.yml
- Removed permission from build-and-deploy-staging.yml
=> chore: :fire: removed permissions gh workflow

.github/workflows/build-and-deploy-test.yml
* Changed build directory to `dist`
* Used `CLOUDFLARE_PROJECT_NAME`  from GH vars
=> Ako/ fix test workflow

.eslintignore, .eslintrc.js, package-lock.json, package.json, rsbuild.config.ts, src/components/blockly-loading/blockly-loading.tsx, src/components/flyout/flyout.tsx, src/components/flyout/help-contents/flyout-help-base.tsx, src/components/shared/styles/constants.scss, src/components/shared/styles/mixins.scss, src/external/bot-skeleton/scratch/hooks/css.js, src/external/bot-skeleton/scratch/index.scss, src/stores/flyout-help-store.ts, src/stores/load-modal-store.ts, src/utils/help-content/help-content.config.ts
- Trying Rsbuild and compare with WebPack to see if there is any improvement in build performance
=> [BOT] Shafin/bot 1970/chore rsbuild

.github/workflows/build-and-deploy-test.yml
- removed the npmrc since it is not required
- fixed preview link
=> chore: :fire: updated test link yml

src/external/bot-skeleton/services/api/chart-api.js
- added temporary console on initialisation of chart api web socket instance to check on staging when it works
=> chore: :fire: added comment on init chart ws instance

.github/workflows/build-and-deploy-test.yml, src/external/bot-skeleton/services/api/chart-api.js
- Removed console from chart-api
=> ci: :zap: removed comment from char api

.github/workflows/sync-translations.yml
- Added sync translations yml for integration of deriv.com/translations
=> Farabi/bot-2002/integrate deriv-com translations

jest.config.ts, src/app/App.tsx, src/external/bot-skeleton/services/api/appId.js, src/pages/endpoint/__tests__/endpoint.spec.tsx, src/pages/endpoint/endpoint.scss, src/pages/endpoint/index.tsx, src/utils/tmp/dummy.tsx
- Added endpoint page
- Added routes component to switch between routes
=> chore: add endpoint page to update server_url and app_id

index.html, src/app/App.tsx, src/app/AuthProvider.tsx, src/app/app-root.scss, src/app/app-root.tsx, src/app/app.scss, src/components/layout/header/account-switcher.tsx, src/components/layout/main-body/index.tsx, src/components/route-prompt-dialog/route-prompt-dialog.tsx, src/external/bot-skeleton/services/api/appId.js, src/hooks/api/account/useActiveAccount.tsx, src/hooks/useStore.tsx, src/hooks/useThemeSwitcher.tsx, src/pages/endpoint/__tests__/endpoint.spec.tsx, src/pages/endpoint/index.tsx
- Remove loader from useStore
- Update layout components to not completely depend on store for initial render
- Added app-root to load app content when store is loaded
=> chore: load app layout without store dependancy

.github/workflows/build-and-deploy-production.yml
- Added production workflow for
=> feat: :zap: added prod workflow

index.html, package-lock.json, package.json, src/app/App.tsx, src/app/app-content.jsx, src/components/shared/utils/config/config.ts, src/components/shared/utils/constants/contract.ts, src/pages/bot-builder/quick-strategy/descriptions/strategy-description.tsx, src/pages/tutorials/faq-content/index.tsx, src/stores/app-store.ts, src/types/dbot.types.ts, src/utils/gtm.ts, src/utils/tmp/dummy.tsx
- Replaced dangerouslySetInnerHTML with react-html-parser
- Resolved following TODOs
- 1
=> Sandeep/bot-2292 - bug fixing and resolving TODOs

index.html, src/app/App.tsx, src/pages/main/main.tsx
- Added defer = true for gtm initialization
- To update the hash use useNavigation instead of directly manipulating the window.location
=> fix: :fire: push hash using react-router-dom

index.html, src/app/App.tsx
- GTM moved to index file for testing
=> refactor: :fire: gtm relocated to index file

index.html, src/app/app-content.jsx, src/pages/main/main.tsx, src/utils/gtm.ts
- Added lazy loading for dashboard, chart and tutorial components
- Also added corresponding Suspense to show the loader
=> refactor: :fire: added lazy loading for dashboard, chart and tutorial components

package-lock.json, package.json, src/app/app-content.jsx, src/pages/bot-builder/quick-strategy/config.ts, src/pages/bot-builder/quick-strategy/form-wrappers/desktop-form-wrapper.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/mobile-form-wrapper.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/qs-stepper.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-list.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-template-picker.scss, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-template-picker.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/trade-constants.ts, src/pages/bot-builder/quick-strategy/quick-strategy.scss, src/pages/bot-builder/quick-strategy/quick-strategy.tsx, src/pages/dashboard/announcements/announcements.tsx, src/pages/dashboard/announcements/config.tsx
[App Separation] - Update new Quick Strategy Changes
=> [App Separation] - Update new Quick Strategy Changes

src/pages/bot-builder/quick-strategy/form-wrappers/qs-stepper.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-list.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-template-picker.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/trade-constants.ts
fix: Translation issues in Quick strategy
=> [BOT]maryia/GRWT-1246/fix: Translation issues in Quick strategy

src/components/layout/header/account-info-loader.tsx, src/components/load-modal/section-message/section-message.scss, src/components/shared_ui/autocomplete/autocomplete.scss, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-template-picker.scss, src/pages/bot-builder/quick-strategy/quick-strategy.scss
fix: [App Separation] UI Bugs (part 1)
=> [BOT]maryia/BOT-2338/fix: [App Separation] UI Bugs (part 1)

src/components/layout/header/account-switcher.tsx, src/components/layout/header/utils/index.js, src/external/bot-skeleton/services/api/api-base.ts
Added DIEL logics in the account switcher
=> Rupato/bot 2201/account switcher diel logic

src/app/app.scss, src/components/layout/header/menu-items/menu-items.tsx
fix: [App Separation] UI Bugs (part 2)
=> maryia/BOT-2340/fix: [App Separation] UI Bugs (part 2)

.github/workflows/build-and-deploy-production.yml, .github/workflows/build-and-deploy-staging.yml, .github/workflows/build-and-deploy-test.yml, src/utils/analytics/index.ts
- Added growthbook, rudderstack key and remote config url to production and staging workflows
=> Farabi/bot-2365/configure-growthbook-and-rudderstack 

src/components/layout/header/mobile-menu/toggle-button.tsx, src/components/shared_ui/drawer/drawer.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/external/bot-skeleton/services/api/chart-api.js, src/pages/chart/chart.tsx, src/pages/chart/toolbar-widgets.tsx, src/pages/dashboard/bot-list/index.scss, src/pages/dashboard/bot-list/recent-workspace.tsx, src/pages/tutorials/tutorials.scss
This pull request includes several changes to improve the user interface and codebase consistency across various components. The most important changes include modifying icons, updating device detection logic, and adjusting styles for better responsiveness.
* [`src/components/layout/header/mobile-menu/toggle-button.tsx`](diffhunk://#diff-3b6295cbd11c23da0ffbbc50d15e0ae08cb7de5e5a879747ce798002af79c5c9L9-R9): Simplified the `ToggleButton` component by removing unnecessary class attributes from the button element.
* [`src/components/shared_ui/drawer/drawer.tsx`](diffhunk://#diff-ede15ed59dd2a1315a504a2a1738f2c587d7238b38a0d9cf16c37c7c8ec7388eL3-R3): Replaced `LabelPairedChevronUpLgBoldIcon` with `LegacyChevronUp2pxIcon` for better visual consistency. …
=> fix: ui issues

.github/workflows/build-and-deploy-production.yml, package-lock.json, package.json, src/app/app-content.jsx, src/hooks/useTrackjs.ts
- Added trackjs hook to use and initialize trackjs
- Added Bundle Analyzer script to generate package size report (Dev Only)
=> feat: :fire: added trackjs implementation and bundle analyzer script

.github/workflows/build-and-deploy-production.yml, .github/workflows/build-and-deploy-staging.yml, package-lock.json, package.json, src/app/app-content.jsx, src/hooks/useTrackjs.ts, src/utils/datadog.ts
=> feat: :fire: Added the datadog

src/components/flyout/flyout.tsx, src/components/layout/header/header.tsx, src/pages/bot-builder/quick-strategy/form.tsx, src/pages/bot-builder/quick-strategy/selects/growth-rate-type.tsx, src/stores/client-store.ts, src/stores/flyout-store.ts, src/stores/root-store.ts, src/stores/run-panel-store.ts, src/stores/toolbox-store.ts, src/utils/gtm.ts
This pull request includes several changes to the `src` directory, primarily focusing on refactoring imports, improving the `GTM` utility usage, and minor code cleanups.
* [`src/components/flyout/flyout.tsx`](diffhunk://#diff-7052e619cac3aaa3cf2396e750b0bdf78107b9238de6bb0a00896f223a753368R5): Added import for `GTM` and removed redundant `gtm` store usage. [[1]](diffhunk://#diff-7052e619cac3aaa3cf2396e750b0bdf78107b9238de6bb0a00896f223a753368R5) [[2]](diffhunk://#diff-7052e619cac3aaa3cf2396e750b0bdf78107b9238de6bb0a00896f223a753368L185) [[3]](diffhunk://#diff-7052e619cac3aaa3cf2396e750b0bdf78107b9238de6bb0a00896f223a753368L200-R206)
* [`src/components/layout/header/header.tsx`](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L1): Removed unused imports …
=> fix: unable to run bot in real account

jest.config.ts, package-lock.json, package.json, src/app/App.tsx, src/app/CoreStoreProvider.tsx, src/app/app-content.jsx, src/components/layout/header/account-switcher.tsx, src/components/layout/header/header.tsx, src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx, src/components/layout/index.tsx, src/hooks/auth/useOauth2.ts, src/pages/callback/callback-page.tsx, src/pages/callback/index.ts, src/stores/run-panel-store.ts
This pull request includes significant updates to the authentication system, primarily focusing on integrating OAuth2 and improving the logout functionality across various components. Additionally, it introduces a new callback page and adjusts dependencies.
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L1-L8): Removed URLUtils-based login info handling and added a new route for the `CallbackPage` component. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L1-L8) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R50-L81)
* [`src/app/CoreStoreProvider.tsx`](diffhunk://#diff-5ec7969cf78888b570b3224805b4252b136ff69101053e09e361de4be5cdded8R7): Integrated OAuth2 …
=> chore: implement silent login

src/components/layout/footer/index.tsx, src/components/layout/header/header.tsx, src/components/layout/header/mobile-menu/mobile-menu.tsx, src/components/tnc-status-update-modal/tnc-status-update-modal.scss, src/utils/getActiveTabUrl.ts
- Reload app on language change for mobile language switcher
=> farabi/bot-2424/tutorial-and-bot-builder-translation-on-mobile 

package-lock.json, package.json, src/components/journal/journal-components/filters.tsx, src/components/layout/header/account-switcher.tsx, src/components/layout/header/header.scss, src/components/shared_ui/checkbox/checkbox.scss, src/components/shared_ui/checkbox/checkbox.tsx, src/stores/journal-store.ts, src/stores/run-panel-store.ts, src/utils/analytics/index.ts
This pull request includes several changes across multiple files to improve functionality and fix issues. The most important changes include updating dependencies, modifying account switcher behavior, enhancing checkbox component, and refining error handling.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L28-R28): Updated `@deriv-com/ui` dependency from version `^1.36.4` to `^1.37.1`.
* [`src/components/layout/header/account-switcher.tsx`](diffhunk://#diff-bf3f2df057110808659b78456c70e733dec577bee954e3fc8391016c313164d1R32): Added `activeLoginId` prop to `TAccountSwitcherProps` and `RenderAccountItems` to enable specific behavior based on the active account. [[1]](diffhunk://#diff-bf3f2df057110808659b78456c70e733dec577bee954e3fc8391016c …
=> chore: fix journal filter and add reset balance for demo

src/app/App.tsx, src/public-path.ts
Added the survicate script for the standalone
=> Rupato/fix: added the survicate script

rsbuild.config.ts
Made changes to the RS build to copy the fonts and shaders
=> Rupato/fix: for charts icons

src/app/CoreStoreProvider.tsx, src/components/layout/header/account-switcher.tsx, src/components/layout/header/header.scss, src/components/layout/header/mobile-menu/menu-content.tsx, src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx, src/components/loader/rectangle-skeleton/index.tsx, src/components/loader/rectangle-skeleton/rectangle-skeleton.scss, src/hooks/auth/useOauth2.ts, src/stores/client-store.ts
This pull request includes several changes to improve the logout functionality and enhance the user interface in various components. The most important changes include updating the `useOauth2` hook, adding a loading skeleton for the logout button, and modifying the `RenderAccountItems` component to use `observer`.
Enhancements to logout functionality:
* [`src/hooks/auth/useOauth2.ts`](diffhunk://#diff-7ed7d4a03c35423f9e58a16d28f0b5af98eee2e3f4e729a311f562cd8b5d268bR1): Updated the `useOauth2` hook to accept a `client` parameter and added a `logoutHandler` to handle the logout process and set the `is_logging_out` state. [[1]](diffhunk://#diff-7ed7d4a03c35423f9e58a16d28f0b5af98eee2e3f4e729a311f562cd8b5d268bR1) [[2]](diffhunk://#diff-7ed7d4a03c35423f9e58a16d28f0b5af98eee2e3f4e729a311f562cd8b5 …
=> chore: fix logout issue and account switcher style issues

package-lock.json, package.json
This pull request includes a small update to the `package.json` file. The change involves updating the version of the `@deriv-com/auth-client` dependency to a newer version.
Dependency update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L25-R25): Updated `@deriv-com/auth-client` dependency from version `^1.2.15` to `^1.3.1`.
=> chore: update auth client package

src/stores/transactions-store.ts
fix: Total Payout remains zero for multipliers and accumulator QS
=> maryia/fix: Total Payout remains zero for multipliers and accumulator QS

src/components/layout/header/wallets/account-info-wallets.tsx, src/hooks/useStoreWalletAccountsList.ts
- Show balance for each account on mobile wallet account switcher
- Update balance on header with new balance after contract bought or sold
=> Farabi/bot-2475/wallet-account-switcher-bugs 

index.html, src/app/CoreStoreProvider.tsx, src/app/app-content.jsx, src/components/layout/header/header.tsx, src/stores/google-drive-store.ts, src/utils/gtm.ts
This pull request includes several changes aimed at improving the initialization and handling of third-party scripts, as well as enhancing the logout functionality. The most important changes include adding a delay to the LiveChat script initialization, integrating GTM with the store, and adding a check for OAuth2 logout based on a cookie.
Improvements to script initialization:
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R49-R55): Added a 3-second delay to the initialization of the LiveChat tracking script.
* [`index.html`](diffhunk://#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051L13): Removed the `zaraz` script to clean up unused scripts.
Enhancements to GTM integration:
* …
=> chore: integrate gtm and add delay on loading scripts

src/stores/load-modal-store.ts
=> Rupato/BOT-2607/fix: container error not in the document

src/pages/main/main.scss, src/pages/tutorials/dbot-tours/bot-builder-tour/bot-builder-tour-mobile.tsx, src/pages/tutorials/dbot-tours/utils.ts
Updated the tour file with lastest deriv app changes.
Fixed the blinker animation on load icon.
=> Rupato/BOT-2595/fix: mobile bot builder tour

src/components/shared_ui/money/money.tsx
This pull request includes a small change to the `src/components/shared_ui/money/money.tsx` file. The change wraps the `has_sign && sign` expression in a `span` element to ensure proper rendering.
* [`src/components/shared_ui/money/money.tsx`](diffhunk://#diff-9383eee2a3692e88f8ad4fc93cbcc379b4f7e2f418aea5b1a36f489a2f659fdfL32-R32): Wrapped `has_sign && sign` in a `span` element for better rendering.
=> Rupato/BOT-2630/fix for removechild node on TrackJS

src/app/app-content.jsx
---
- Removed unwanted comments from data dog initialization
- Reduced data dog same rate for prod
=> chore: :fire: removed comments from data dog init

src/external/bot-skeleton/services/tradeEngine/utils/interpreter.js
fix: TrackJS restoreStateSnapshot is not a function
=> maryia/BOT-2658/fix: TrackJS restoreStateSnapshot is not a function

src/constants/contract.ts, src/pages/bot-builder/quick-strategy/form-wrappers/desktop-form-wrapper.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/mobile-form-wrapper.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/mobile-qs-footer.tsx, src/pages/bot-builder/quick-strategy/form-wrappers/strategy-list.tsx, src/pages/bot-builder/quick-strategy/quick-strategy.scss, src/pages/bot-builder/quick-strategy/quick-strategy.tsx, src/pages/bot-builder/quick-strategy/types.ts
Fix Accumulators bugs in production
- Sort Quick Strategies according to chip order
- Fix QS modal footer being hidden (footer should be sticky and always visible)
- Fix padding for QS modal footer buttons on responsive according to design
Figma link:
https://www.figma.com/design/AoZlGgz5Xi3Jc9cJhoDtSn/Deriv-Bot-(Classic-UI)?node-id=13266-7112&node-type=canvas&focus-id=26569-182140&m=dev
=> fix: Fix Accumulators bugs in production

src/external/bot-skeleton/scratch/blocks/Binary/Trade Definition/trade_definition_market.js
=> maryia/feat: enable cryptocurrency

src/components/shared/utils/config/config.ts, src/pages/endpoint/__tests__/endpoint.spec.tsx, src/pages/endpoint/index.tsx
fix: Remove quotation mark "" shown on server from local storage
=> maryia/BOT-2669/fix: Remove quotation mark "" shown on server from local storage

src/app/App.tsx, src/components/shared/utils/config/config.ts
This pull request includes changes to the `src/app/App.tsx` and `src/components/shared/utils/config/config.ts` files to improve currency validation and refactor local storage utility usage. The most important changes are:
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L132-R143): Replaced the currency validation logic to use the parsed client accounts and handle case insensitivity for currency codes. [[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L132-R143) [[2]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L152-R157)
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L132-R143): Updated the check for demo …
=> fix: query param and server url

src/app/App.tsx
This pull request includes changes to the `src/app/App.tsx` file to improve how client accounts are retrieved and logged. The most important changes include combining stored accounts from local storage and cookies, and adding logging for debugging purposes.
Improvements to account retrieval and logging:
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L74-R80): Combined stored accounts from local storage and cookies into a single `client_accounts` object and added logging for debugging.
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R99): Added logging for the selected account to assist with debugging.
=> fix: added cookies to fix silent login

src/app/App.tsx
This pull request includes a change to the `src/app/App.tsx` file to improve the handling of local storage data in the `App` component.
* [`src/app/App.tsx`](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07L73-R73): Modified the `accounts_list` initialization to parse the local storage item directly, ensuring it defaults to an empty object if the item is not found.
=> fix: silent login

src/app/AuthWrapper.tsx
This pull request includes changes to the `src/app/AuthWrapper.tsx` file to improve the handling of account information stored in cookies and local storage. The most important changes involve importing the `js-cookie` library and adding logic to merge and validate account data from cookies and local storage.
Enhancements to account data handling:
* [`src/app/AuthWrapper.tsx`](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR2): Imported the `js-cookie` library to handle cookies more effectively.
* [`src/app/AuthWrapper.tsx`](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR12-R40): Added logic to parse and merge account data from cookies and local storage, including error handling for invalid JSON in the `client.accounts` …
=> fix: silent login implementation

src/app/AuthWrapper.tsx, src/app/types.ts
This pull request introduces several changes to the `src/app/AuthWrapper.tsx` file, focusing on refactoring and improving the authentication logic. The changes include extracting functions for better readability and maintainability, and adding new types for better type safety.
Refactoring and code improvements:
* Extracted `getCookieAccounts`, `storeAccountsToLocalStorage`, `getActiveAccount`, and `authorizeAccount` functions to simplify the `setLocalStorageToken` function. [[1]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR8-R29) [[2]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR40-R81) [[3]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aL50-R95)
* Updated the `initializeAuth` …
=> fix: implementation of query params and cookies

src/components/layout/index.tsx
This pull request includes a change to the `Layout` component in the `src/components/layout/index.tsx` file. The change modifies the conditions under which the `requestOidcAuthentication` function is called to include a new condition and logs a message for debugging purposes.
Changes to authentication logic:
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL37-R53): Updated the `useEffect` dependency array and conditional logic to include `ifClientAccountHasCurrency` and added a `console.log` statement for debugging.
=> fix: oidc search param

src/components/layout/index.tsx, src/pages/callback/callback-page.tsx
This pull request includes changes to handle missing currencies more effectively in the `Layout` and `CallbackPage` components. The most important changes include storing and removing the missing currency in local storage and redirecting based on the presence of a missing currency.
Improvements to handling missing currencies:
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aR47): Added code to store the missing currency in local storage if a currency is missing and to remove it if all currencies are present. [[1]](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aR47) [[2]](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aR56)
* …
=> fix: oidc relogin issue

src/pages/callback/callback-page.tsx
This pull request includes a change to the `CallbackPage` component in `src/pages/callback/callback-page.tsx` to improve the handling of the selected currency.
Improvements to currency selection:
* [`src/pages/callback/callback-page.tsx`](diffhunk://#diff-48442a2313eb74f85495b7177c68f5054c9518faf6198893217e053cb9a7b836L60-R66): Added logic to determine the currency of the first account if the selected currency is invalid, ensuring a fallback mechanism for currency selection.
=> fix: currency param

.github/workflows/build-and-deploy-test.yml
This pull request updates the GitHub Actions workflow configuration to use a newer version of an action for verifying users.
* [`.github/workflows/build-and-deploy-test.yml`](diffhunk://#diff-d63278f79551d70a0ecc23a55e3dc2e84fbd33ca883e2eed36768ae27c245fa5L26-R26): Updated the `verify_user_in_organization` action from version `v1` to `v3` to ensure compatibility with the latest features and improvements.
=> fix: test for actions

src/components/layout/index.tsx
This pull request includes a small change to the `src/components/layout/index.tsx` file. The change adds a console log statement to debug the `query_param_currency` and updates the session storage with the current currency value.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aR80-R81): Added a `console.log` statement to output the `query_param_currency` value and updated the session storage with the current currency.
=> fix: currency on first login

src/app/App.tsx, src/components/layout/index.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/pages/callback/callback-page.tsx
This pull request includes small changes to the codebase, specifically the removal of `console.log` statements to clean up the code.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL80): Removed a `console.log` statement that was logging the `query_param_currency`.
* [`src/pages/callback/callback-page.tsx`](diffhunk://#diff-48442a2313eb74f85495b7177c68f5054c9518faf6198893217e053cb9a7b836L67-L72): Removed a `console.log` statement that was logging the `selected_currency` and related variables.
=> Rupato/fix  for disabled accounts

public/front-channel.html
Implement front channels, which replaced logged_state cookie logic false for automatically logging out (SLO)
=> Adrienne / Add front channels to dbot

src/components/layout/header/menu-items/menu-items.tsx, src/components/shared_ui/input/input.tsx, src/pages/dashboard/bot-list/save-modal/save-modal.tsx
This pull request includes several changes to improve the functionality and maintainability of the `menu-items` component and related files. The most important changes include adding new hooks and utility functions, modifying redirection logic, and updating input handling.
* [`src/components/layout/header/menu-items/menu-items.tsx`](diffhunk://#diff-dc0c6cabb80e41effb7d5b0d9206c0bc3325309eb780758d24a71edb434360b5R2-L4): Added imports for `standalone_routes` and `useIsGrowthbookIsLoaded`, and modified the `MenuItems` component to include new redirection logic and filtering of menu items based on wallet accounts. [[1]](diffhunk://#diff-dc0c6cabb80e41effb7d5b0d9206c0bc3325309eb780758d24a71edb434360b5R2-L4) [[2]](diffhunk://#diff-dc0c6cabb80e41effb7d5b0d9206c0bc3325309eb780758d24a71edb434360b5 …
=> Rupato/fix: the url and cashier links

src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx, src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet.tsx, src/components/layout/header/common/account-swticher-footer.tsx, src/components/layout/header/common/no-non-eu-accounts.tsx, src/components/layout/header/menu-items/menu-items.tsx, src/components/layout/header/platform-switcher/platform-switcher.tsx, src/utils/traders-hub-redirect.ts
This pull request introduces a series of changes aimed at improving URL redirection logic across various components to handle demo accounts more effectively. The updates primarily involve checking if the account is a demo account and adjusting the URL parameters accordingly.
* [`src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx`](diffhunk://#diff-948b4480a9b3fd95a8a64f3416c7af8d1482e4098d2b2d792adf21416d821bd5L9-R9): Added logic to check if the account is a demo account and modify the URL parameters before redirecting. [[1]](diffhunk://#diff-948b4480a9b3fd95a8a64f3416c7af8d1482e4098d2b2d792adf21416d821bd5L9-R9) [[2]](diffhunk://#diff-948b4480a9b3fd95a8a64f3416c7af8d1482e4098d2b2d792adf21416d821bd5L31-R85)
* …
=> fix: account params

src/components/layout/header/header.tsx, src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request includes changes to enhance the detection of demo accounts by utilizing URL parameters. The updates ensure that the account status is accurately identified based on the URL, which reflects changes when the account status updates.
Enhancements to demo account detection:
* [`src/components/layout/header/header.tsx`](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L48-R53): Added logic to check the `account` URL parameter to determine if the account is a demo account. This ensures the status is updated dynamically based on the URL.
* [`src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx`](diffhunk://#diff-d1dbf017cbc6be00aadfd73ef141a2bfdf9f90b8464e96f24ae4f7870bdf6477L58-R62): Updated the `getAccountUrl` function to include …
=> fix: oidc redirect login

src/components/layout/index.tsx
This pull request includes changes to the `src/components/layout/index.tsx` file to enhance the handling of missing currencies and improve the logic for checking OAuth2 and endpoint conditions.
Enhancements to currency handling:
* Modified the `hasMissingCurrency` logic to filter out disabled accounts before checking for missing currencies and added a console log for missing currencies.
Improvements to OAuth2 and endpoint logic:
* Introduced a new constant `checkOIDCEnabledWithMissingAccount` to encapsulate the condition checking for OAuth2 enabled state and missing client currency, and updated the main condition to use this new constant.
=> fix: for oidc disabled accounts

src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet.tsx, src/components/layout/index.tsx
This pull request includes several changes to the account switcher and layout components to improve the handling of token and currency checks. The most important changes are the removal of the token check from the account switcher component and the enhancement of the currency check in the layout component.
* [`src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet.tsx`](diffhunk://#diff-8093d4ae9559ad56dcce6cf76b37866860279c27066a8dc0d2f2e3769d543d7aL26-R28): Removed the token check from the account switcher component to avoid triggering OIDC login when opening the account switcher. This check is now handled in the Layout component.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL53-R74): Updated …
=> fix: added fix for disabled accounts

src/pages/chart/chart-modal/chart-modal-desktop.tsx, src/pages/chart/chart-wrapper.tsx, src/pages/main/main.tsx
This pull request involves refactoring the chart components in the application to introduce a new `ChartWrapper` component. The most important changes include replacing the `Chart` component with the `ChartWrapper` component in various files and adding the new `ChartWrapper` component with additional functionality.
Changes to chart components:
* [`src/pages/chart/chart-modal/chart-modal-desktop.tsx`](diffhunk://#diff-a3b4182272158c3ef062bf549da1c0ed046f5e24d276ffe0152e999867d64881L6-R6): Replaced the `Chart` component with the new `ChartWrapper` component in the `ChartModalDesktop` component. [[1]](diffhunk://#diff-a3b4182272158c3ef062bf549da1c0ed046f5e24d276ffe0152e999867d64881L6-R6) [[2]](diffhunk://#diff-a3b4182272158c3ef062bf549da1c0ed046f5e24d276ffe0152e999867d64881L26-R26) …
=> fix: the chart rerendering issue

src/components/layout/header/header.tsx, src/components/layout/index.tsx, src/hooks/auth/useOauth2.ts
This pull request includes several changes to the `src/components/layout` and `src/hooks/auth` files to improve the handling of OAuth2 and single sign-on (SSO) scenarios. The most important changes are listed below:
* [`src/components/layout/header/header.tsx`](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L36-R39): Added `isSingleLoggingIn` to the OAuth2 hook and updated the account section rendering logic to handle this new state.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL8-L10): Updated the import statement to include `Loader` and replaced `SSOLoader` with `Loader` for better handling of the single login state. [[1]](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b7 …
=> fix: remove the oidc loader

src/pages/bot-builder/quick-strategy/selects/symbol.tsx
fix: removed clearing of input value on onfocus event
=> Moiz-BOT-2743-Placeholder being removed when dropdown is selected

src/pages/dashboard/bot-list/save-modal/icon-radio.tsx
fix: Removed logic for connect disconnect button on gdrive icon for save strategies modal
=> Moiz-BOT-2750-Gdrive disconnect button improvement Save Strategies Modal

src/pages/tutorials/dbot-tours/bot-builder-tour/bot-builder-tour-desktop.tsx, src/pages/tutorials/dbot-tours/onboarding-tour/onboarding-tour-desktop.tsx, src/pages/tutorials/dbot-tours/tour-content.tsx
Updated Onboarding Tour title and disable overlay click dismissal added properties to react jeyride wrapper to disable dismissal when overlay is clicked
=> Moiz-BOT-2774-Onboarding and Bot Builder Tour bug fixes.

package-lock.json, package.json, src/app/CoreStoreProvider.tsx, src/components/layout/header/header.tsx, src/components/layout/index.tsx, src/hooks/auth/useOauth2.ts, src/hooks/useInvalidTokenHandler.ts
This pull request includes several changes focused on removing the `isOAuth2Enabled` property and improving the OAuth2 login flow. The most important changes include updates to dependencies, modifications to components that previously used `isOAuth2Enabled`, and the addition of a new hook for handling invalid tokens.
* Updated the `@deriv-com/auth-client` dependency version in `package.json` from `^1.4.3` to `^1.4.6`.
* Removed `isOAuth2Enabled` from the `CoreStoreProvider` component in `src/app/CoreStoreProvider.tsx`.
* Removed `isOAuth2Enabled` from the `AppHeader` component in `src/components/layout/header/header.tsx`. [[1]](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L36-R36) [[2]](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee …
=> fix: oidc issues to remove the loader and removed isOauthEnabled

src/external/bot-skeleton/scratch/hooks/block_svg.js, src/external/bot-skeleton/scratch/hooks/workspace_svg.js
Added highlighting functionality for new blocks added to the bot builder and highlight being transfered to the latest added block
=> Moiz - BOT-2748 - Highlight the blockly upon import from block menu

src/app/app-root.tsx
This pull request introduces additional debugging logs to the `AppRoot` component in `src/app/app-root.tsx`. These logs provide insights into the API initialization process.
Debugging improvements:
* Added three `console.log` statements to log the initialization status of `api_base`, the `api_base` object itself, and the state update for `is_api_initialized`. These logs are intended to aid in debugging the API initialization flow.
=> fix: added console to debug

src/app/app-root.tsx
This pull request enhances error handling and logging in the `AppRoot` component. The most important changes include wrapping the API initialization logic in a `try-catch-finally` block to handle potential errors and adding additional debug logs for better traceability.
* Wrapped the API initialization logic in a `try-catch-finally` block to handle potential errors during the initialization process. If an error occurs, it logs the error and sets `api_base_initialized.current` to `false` to ensure proper state management. (`src/app/app-root.tsx`, [src/app/app-root.tsxL45-R64](diffhunk://#diff-94879295562881d6d113d5d186e88ce8f3e5357139e22d4d8b73b250914133a8L45-R64))
* Added debug logs for the API initialization process, including messages for the `try`, `catch`, and `finally` blocks, as …
=> fix: store load

src/components/layout/index.tsx, src/utils/index.ts
This pull request includes two changes: one refactor to simplify rendering logic in the `Layout` component and one enhancement to the `isDotComSite` utility function.
* [`src/components/layout/index.tsx`](diffhunk://#diff-297411bbdb20a2ca96207a6e5284cd0598f90d22b776fa55232a04fae431835aL163-R163): Simplified the rendering logic by removing the redundant conditional check for `isSingleLoggingIn` when rendering the `<Outlet />` component.
* [`src/utils/index.ts`](diffhunk://#diff-6147e3c1761df71fd40952dbcbac388a45f80b8c318f367ef41048351a2c0c99L6-R10): Enhanced the `isDotComSite` function to also return `true` if the site is running on `localhost`, in addition to `.com` domains. Updated the function's documentation to reflect this change.
=> Load outlet when sso is false

src/components/bot-notification/bot-notification-utils.ts
fix: updated bots reports snackbar text
=> Moiz-BOT-2735-Improvement - Reports redirection from floating banner 

src/app/App.tsx, src/components/layout/index.tsx, src/components/shared/utils/currency/currency.ts, src/external/bot-skeleton/services/api/ticks_service.js, src/pages/callback/callback-page.tsx, src/stores/client-store.ts
This pull request introduces improvements to currency validation, refactors how invalid currencies are handled, and updates the logout process to ensure API consistency. The changes streamline the codebase and enhance user experience by ensuring valid currency handling across different components.
* Added `crypto_currencies_display_order` and `fiat_currencies_display_order` imports to `src/app/App.tsx` and `src/pages/callback/callback-page.tsx` for unified currency validation. (`[[1]](diffhunk://#diff-7c79023b16fd616788af0fdcb31d619ae04da7259aa564fd72fb0ea07d8ebe07R7)`, `[[2]](diffhunk://#diff-48442a2313eb74f85495b7177c68f5054c9518faf6198893217e053cb9a7b836R2)`)
* Introduced `validCurrencies` and `is_valid_currency` checks in `App` and `CallbackPage` to ensure only valid currencies are …
=> fix: oidc rpc logout

src/app/AuthWrapper.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/external/bot-skeleton/services/api/ticks_service.js, src/pages/callback/callback-page.tsx, src/utils/auth-utils.ts
This pull request introduces a utility function, `clearAuthData`, to handle clearing authentication-related data from local storage and reloading the page. This utility is integrated across multiple files to ensure proper handling of invalid or expired authentication states.
* **New Utility Function**: Added `clearAuthData` in `src/utils/auth-utils.ts` to centralize the logic for clearing authentication data and reloading the page.
* **Integration in `AuthWrapper.tsx`**:
- Imported `clearAuthData` and updated the `setLocalStorageToken` function to clear local storage when `logged_state` is `false`. [[1]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR6) [[2]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR49-R53)
* …
=> fix: for invalid token

src/app/app-content.jsx, src/components/auth-loading-wrapper/index.tsx, src/components/layout/header/header.tsx, src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx, src/components/layout/index.tsx, src/components/shared/utils/routes/routes.ts, src/external/bot-skeleton/services/api/api-base.ts, src/stores/app-store.ts
This pull request introduces an `AuthLoadingWrapper` component to handle user authentication states and integrates it into the application. It also updates various components and utilities to improve user experience during the login process and streamline account settings navigation.
* Added a new `AuthLoadingWrapper` component in `src/components/auth-loading-wrapper/index.tsx` to display a fullscreen loader when the user is in the process of logging in (`isSingleLoggingIn`).
* Integrated `AuthLoadingWrapper` into the `AppContent` component in `src/app/app-content.jsx` to wrap the main application content. This ensures a smoother user experience during authentication. [[1]](diffhunk://#diff-acb1b12c8798bdef78154e1bcbb70ce985402145ca80e436a5886cb66afed67fR4) …
=> fix: invalid token check

src/pages/tutorials/dbot-tours/common/tour-start-dialog.tsx
This pull request introduces a minor update to the `TourStartDialog` component in the `src/pages/tutorials/dbot-tours/common/tour-start-dialog.tsx` file. The change adds an additional localized message to the onboarding tour dialog.
Changes to the onboarding tour dialog:
* [`src/pages/tutorials/dbot-tours/common/tour-start-dialog.tsx`](diffhunk://#diff-c7e4d0d44017d25ba5726da2f0f7bad6cc28eb51f9d6cc79c63ec27bca326e86R54-R65): Added a new localized message, `"Hello World"`, within the onboarding tour dialog to enhance the user experience.
=> fix: hello world

src/app/app-root.tsx, src/components/layout/header/AccountSwitcherWallet/account-switcher-wallet-mobile.tsx, src/components/layout/header/header.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/hooks/growthbook/useGrowthbookGetFeatureValue.ts, src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx, src/pages/callback/callback-page.tsx, src/utils/traders-hub-redirect.ts
This pull request includes several changes focused on removing test `console.log` statements, updating feature flag usage for GrowthBook, and improving code readability. The most significant updates involve cleaning up debugging logs, ensuring consistent feature flag naming, and implementing logic for country-based redirection.
* Removed multiple test `console.log` statements across various files, including `src/app/app-root.tsx`, `src/external/bot-skeleton/services/api/api-base.ts`, `src/pages/bot-builder/quick-strategy/inputs/qs-input.tsx`, and `src/pages/callback/callback-page.tsx`. These were likely used for debugging purposes and are no longer necessary. [[1]](diffhunk://#diff-94879295562881d6d113d5d186e88ce8f3e5357139e22d4d8b73b250914133a8L46-L54) …
=> Redirection to high code

src/external/bot-skeleton/services/api/api-base.ts
This pull request removes a debug `console.log` statement from the `APIBase` class in `src/external/bot-skeleton/services/api/api-base.ts`. The change helps clean up the code by eliminating unnecessary logging.
Code cleanup:
* Removed a `console.log` statement that logged the token during the authorization process in the `APIBase` class. This improves code cleanliness and prevents potential exposure of sensitive information.
=> fix: removed console.log

src/constants/quick-strategies/d_alembert.ts, src/constants/quick-strategies/martingale.ts, src/constants/quick-strategies/oscars_grind.ts, src/constants/quick-strategies/reverse_dalembert.ts, src/constants/quick-strategies/reverse_martingale.ts, src/constants/quick-strategies/strategy_1_3_2_6.ts
updated tutorial texts to new content provided in designs and doc
=> Moiz-Bot 2755-Tutorial Improvements on Dbot 

src/app/App.tsx, src/components/bot-notification/bot-notification-utils.ts, src/components/layout/index.tsx, src/components/shared/utils/currency/currency.ts, src/components/shared_ui/dialog/dialog.tsx, src/components/transactions/transactions.scss, src/external/bot-skeleton/services/api/ticks_service.js, src/pages/callback/callback-page.tsx, src/pages/main/main.tsx, src/stores/client-store.ts, src/stores/run-panel-store.ts
fix: 
Added oidc implementation to main dialog wrapper and passed to dialog
Updated dialog options and close and submit handlers in the run-store
Added checks in dialog implementation to trigger oidc when text of button clicked is login
=> Moiz- BOT-1821- Add a logged out view of the desktop platform

src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request refactors the `useMobileMenuConfig` hook in `src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx` to improve performance by memoizing the menu configuration and tracking dependencies more effectively. The changes primarily involve introducing `useMemo` and adding dependency tracking for client-related properties.
* [`src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx`](diffhunk://#diff-d1dbf017cbc6be00aadfd73ef141a2bfdf9f90b8464e96f24ae4f7870bdf6477L81-R87): Added `useMemo` to memoize the `menuConfig` array, ensuring it only recalculates when relevant dependencies (`is_virtual`, `currency`, `is_logged_in`) change. [[1]](diffhunk://#diff-d1dbf017cbc6be00aadfd73ef141a2bfdf9f90b8464e96f24ae4f7870bdf6477L81-R87) …
=> fix: redirection for traders hub

src/pages/dashboard/announcements/announcements.tsx
fix: Updated object.hasown to use object.prototype to better support older devices
=> Moiz-BOT-2659-TrackJs: Object.hasOwn is not a function

src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request enhances the `useMobileMenuConfig` function in `src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx` by introducing logic to dynamically determine redirect URLs based on user attributes and feature flags. It also includes a new utility hook to fetch feature flag values.
* Added import for `useGrowthbookGetFeatureValue` to fetch feature flag values, enabling dynamic behavior based on feature configurations.
* Introduced `featureFlagValue` to retrieve the `hub_enabled_country_list` feature flag, which is later used for conditional logic.
* Added `has_wallet` check to determine if the user has a wallet account.
* Implemented `getRedirectUrl` function to decide the redirect URL based on whether the user's country is in the hub-enabled country list and whether …
=> fix: wallet enabled redirection check

src/app/app.scss, src/pages/main/main.scss, src/pages/main/main.tsx
Added css class to disable touch events for backdrop to fix scrollable issue
Added gradients to left and right side of navigation tabs
Added intersection observer to hide/show gradient based of if elements are hidden or not
=> Moiz-Bot 2752-[DBot] UI minor bugs and improvement

src/external/bot-skeleton/services/api/api-base.ts
=> Moiz-GRWT-5598-Outdated Announcements

src/components/trading-assesment-modal/index.tsx, src/pages/main/main.scss
fix: update link to go to staging
=> Moiz-BOT-2795-Updated navigation link for staging to go to staging

src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx
This pull request introduces debugging logs to the `useMobileMenuConfig` function to provide insights into key variables during runtime. These changes are aimed at facilitating the debugging process by logging the values of specific flags and conditions.
* [`src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx`](diffhunk://#diff-d1dbf017cbc6be00aadfd73ef141a2bfdf9f90b8464e96f24ae4f7870bdf6477L95-R98): Added `console.log` statements to log the values of `featureFlagValue?.hub_enabled_country_list`, `client?.residence`, `is_hub_enabled_country`, and `has_wallet` for debugging purposes.
=> fix: test issue

src/pages/callback/callback-page.tsx
=> Revert "fix: currency"

src/components/layout/index.tsx
=> Revert "fix: check logs"

src/pages/callback/callback-page.tsx
=> Revert "fix: first login currency"

src/app/AuthWrapper.tsx, src/components/layout/header/menu-items/menu-items.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/utils/auth-utils.ts, src/utils/traders-hub-redirect.ts
This pull request introduces several changes across multiple files to enhance functionality related to user country management, redirection logic, and Traders Hub links. The most significant updates include storing the user's country in `localStorage`, improving redirection logic based on the user's country, and refactoring the `TradershubLink` component to handle dynamic URLs.
* Added logic to store the user's country (`authorize.country`) in `localStorage` in both `AuthWrapper.tsx` and `APIBase` to make the country accessible across the application. (`[[1]](diffhunk://#diff-af63e738f04e9a6ee6aa4a007406f027572f6c9ba0d97b9dadc0f2e36d13521aR56)`, `[[2]](diffhunk://#diff-3b0931891357dd6358fa53dcd1ab528d4de6ec5e344c41956adbe694df9e4c89R187)`)
* Updated `clearAuthData` in `auth-utils.ts` to …
=> fix: th redirect issue

package-lock.json, package.json, src/app/AuthWrapper.tsx, src/components/layout/header/header.tsx, src/components/layout/header/mobile-menu/use-mobile-menu-config.tsx, src/components/layout/index.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/hooks/useTMB.ts, src/pages/callback/callback-page.tsx, src/pages/main/main.tsx, src/stores/app-store.ts
This pull request introduces significant changes related to the implementation of a new feature flag, `is_tmb_enabled`, which impacts authentication flows and session management. It includes updates to various components, hooks, and utilities to support this feature. Additionally, some cleanup and refactoring have been performed to remove unnecessary logs and improve code readability.
* **New Hook for TMB Support**: Added a new `useTMB` hook to manage TMB-related logic, including session checks, token processing, and logout handling. This hook centralizes the logic for determining if TMB is enabled and provides utility functions like `onRenderTMBCheck`. (`src/hooks/useTMB.ts`)
* **Integration Across Components**:
* Updated `AppHeader`, `Layout`, and `AppWrapper` components to …
=> Rupato/fix: implementation of TMB

src/hooks/useTMB.ts
This pull request refactors the `useTMB` hook in `src/hooks/useTMB.ts` to improve code clarity and maintainability by introducing a utility function for environment checks. The most important changes include replacing conditional logic with the `isStaging_util` function and importing it from a shared utility module.
* [`src/hooks/useTMB.ts`](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958R5): Added the `isStaging_util` import from `@/components/shared/utils/url/helpers` to centralize environment logic.
* [`src/hooks/useTMB.ts`](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L52-R55): Replaced the inline conditional logic for determining the environment with the `isStaging_util` function in the `isTmbEnabled` method, …
=> fix: isStagin check

src/app/app-root.tsx
This pull request introduces changes to the `AppRoot` component in `src/app/app-root.tsx` to improve the initialization flow by decoupling the TMB (Toggle Management Backend) status check from API initialization. It ensures better handling of asynchronous operations and adds a timeout fallback mechanism for API initialization.
* **Added state management for TMB status check**: Introduced `is_tmb_check_complete` and `setIsTmbCheckComplete` to track the completion of the TMB status check independently of API initialization.
* **Separated TMB status check logic**: Implemented a new `useEffect` to asynchronously check TMB status (`checkTmbStatus`) and handle errors gracefully.
* **API initialization timeout fallback**: Added a timeout mechanism to initialize the API if the TMB status check …
=> fix: active symbol call

src/app/CoreStoreProvider.tsx
This pull request makes minor updates to the `CoreStoreProvider` component in `src/app/CoreStoreProvider.tsx`. The changes focus on improving conditional checks and updating dependency arrays for hooks.
Updates to conditional checks:
* Added a check to ensure `api_base.api` exists before proceeding with the `websiteStatus` call in the `useEffect` hook.
Updates to dependency arrays:
* Included `is_tmb_enabled` in the dependency array of the `useEffect` hook to ensure the effect re-runs when this value changes.
=> fix: for core store provider

src/app/app-root.tsx, src/components/layout/header/header.tsx, src/hooks/useTMB.ts
This pull request focuses on removing excessive logging and improving the `onRenderTMBCheck` function to handle an optional parameter for better control during login button-triggered actions. These changes aim to clean up the codebase and enhance functionality.
* Removed redundant `console.log` statements across multiple files, including `src/app/app-root.tsx`, `src/components/layout/header/header.tsx`, and `src/hooks/useTMB.ts`, to reduce unnecessary clutter in the logs. [[1]](diffhunk://#diff-94879295562881d6d113d5d186e88ce8f3e5357139e22d4d8b73b250914133a8L67) [[2]](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L140-L148) [[3]](diffhunk://#diff-369c35ed105770696d1e076b245f598bf8b44660ac3fefe85ee26b5f31e5b7c3L163-L164) …
=> fix: redirection

src/components/trade-animation/trade-animation.tsx, src/hooks/useTMB.ts, src/stores/self-exclusion-store.ts
This pull request introduces several improvements to error handling, logging, and conditional checks across the codebase. The most important changes include adding a conditional check for logged-in status before performing self-exclusion checks, improving logging clarity for a specific error case, and enhancing error handling when fetching self-exclusion data.
* [`src/components/trade-animation/trade-animation.tsx`](diffhunk://#diff-c2fdd1b296d39bf2cc95d7924d9498678ae883af38b66bdc7ac0207abe30c085R46): Added a conditional check to ensure the `performSelfExclusionCheck` function is only called if the client is logged in and has a valid `loginid`.
* [`src/hooks/useTMB.ts`](diffhunk://#diff-1693c842cbdff131e5a6d04a38e26e478527cfc01996cdc0d2ff41c37f551958L309-R309): Replaced an error log with …
=> fix: tmb trackjs issues

src/stores/self-exclusion-store.ts
This pull request includes a small change to the error handling logic in the `SelfExclusionStore` class. The change improves flexibility by accommodating different error structures when checking for the `AuthorizationRequired` error code.
=> Rupato/TrackJS fix--fix: self exclusion data

src/hooks/useTMB.ts
This pull request refactors the `getActiveSessions` function in the `useTMB` hook to improve flexibility and error handling when determining the OAuth sessions URL. The changes introduce a configuration-based URL approach while maintaining a fallback for domain-based URLs.
* Added support for fetching the OAuth sessions URL from the `config.server_url` value in `localStorage`, allowing for dynamic configuration. If available, this URL is prioritized.
* Added error handling for the HTTP response, throwing an error if the response is not OK, with the status code and text included in the error message.
* Introduced a `console.log` statement to log the `config.server_url` being used for debugging purposes.
* Simplified the fallback mechanism for determining the OAuth URL based on the current …
=> fix: tmb fallback to oauth session

src/hooks/useTMB.ts
This pull request refactors the `useTMB` hook in `src/hooks/useTMB.ts` to improve the handling of session URLs and logging. The changes ensure protocol consistency for the `config.server_url` and streamline the logic for determining fallback session URLs.
* Ensured that `config.server_url` includes the correct protocol by prepending `https://` if it is missing. This prevents potential issues with improperly formatted URLs.
* Simplified the logic for determining fallback session URLs based on the hostname by removing redundant variables and directly assigning the appropriate URL.
* Added a log statement to indicate when a request is being made to the `sessions/active` endpoint, improving traceability during debugging.
=> fix: session url

public/sw.js
This pull request improves the service worker's fetch event handling in `public/sw.js` to prevent caching and interference with critical asset, authentication, and API requests. The main changes include more robust filtering of requests that should bypass the service worker, which helps avoid chunk loading errors and authentication issues.
**Enhanced request filtering in the fetch event:**
* Added logic to skip JavaScript and CSS chunk requests to prevent chunk loading errors.
* Implemented checks to skip authentication requests using a new `isAuthRequest` helper, covering various OAuth, OIDC, and third-party providers. [[1]](diffhunk://#diff-98fd1d4c44ad3934ee242b1f070d235cc39f11e46738f28de66c6740182c4706R88-R122) [[2]](diffhunk://#diff-98fd1d4c44ad3934ee242b1f070d235cc39f11e46738f28de66c …
=> fix: servic-eworker-cache-implementation

index.html, src/utils/pwa-utils.ts
This pull request updates the service worker registration logic to prevent issues with chunk loading and login on Firefox and Safari browsers. The changes ensure that service workers are not registered on these browsers, and any existing service workers are unregistered to avoid potential problems. The logic for handling service worker messages is also updated to only apply to supported browsers.
**Browser compatibility and service worker handling:**
* Updated `index.html` to detect Firefox and Safari browsers, and prevent service worker registration on those browsers to avoid chunk loading issues. Existing service workers are also unregistered for these browsers.
* Updated `src/utils/pwa-utils.ts` to prevent service worker registration on Firefox and Safari, with improved console …
=> fix: safari chunk issue

public/sw.js
This pull request refactors the logic for identifying authentication and API requests in the `public/sw.js` service worker file. The main improvement is the introduction of a secure domain validation helper, which enhances the accuracy and security of domain checks by ensuring requests are only matched against allowed domains or their subdomains.
**Refactoring for secure domain validation:**
* Added a new helper function `isAllowedDomain` to both `isAuthRequest` and `isApiRequest` for checking if a hostname matches an allowed domain or its subdomain, improving security and correctness.
**Authentication request detection improvements:**
* Updated the domain checks in `isAuthRequest` to use `isAllowedDomain` instead of simple substring matching, covering Deriv-specific and third-party auth …
=> fix: resolve Incomplete URL substring sanitization

package-lock.json, package.json, src/components/trade-animation/trade-animation.tsx, src/external/bot-skeleton/services/api/api-base.ts, src/hooks/useTMB.ts, src/pages/callback/callback-page.tsx
=> Revert "Mayuran/check revert resize"

src/external/bot-skeleton/scratch/backward-compatibility.js, src/external/bot-skeleton/scratch/dbot.js
This pull request introduces minor improvements to the bot skeleton codebase, focusing on robustness and reliability in variable handling and block structure navigation.
Code robustness and reliability:
* Improved variable name extraction by using a utility function that checks both `textContent` and `innerText`, ensuring compatibility with different DOM structures in `BlockConversion`.
* Added a guard clause to prevent errors when the top parent block is missing in the `DBot` class, enhancing stability during block navigation.
=> fix: leagacy conversion
